### ISSUE TITLE
Add ability to run output configs

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1028]
The json results files outputted by Armory currently can't be used as inputs to subsequent Armory runs. Ideally one could `armory run` one of these files and yield a new results file with the results fields modified to those of the subsequent run.

**Comment by mwartell** [comment]
We're actually pretty close to this, now that the results fully incorporates the config plus commandline overrides https://github.com/twosixlabs/armory/pull/1027.  Is that not what this issue wanted?

**Comment by lcadalzo** [comment]
When I revisited this earlier today, I thought it seemed a bit counter-intuitive the notion of "running" a results file.
