### ISSUE TITLE
refactor evaluator for stepwise execution and probe-points

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1041]
Separate the multiple stages in the execution of a configuration so:
1. phases are segregated (for example, benign and adversarial execution)
2. inter-phase results are stored for debugging or re-run
3. make clear documentation of the internal process

**Comment by mwartell** [comment]
I have refactored `Scenario` subclasses to (optionally) split out the functional groups in `_evaluate`. The setup stages

1. config 
2. model
3. defense
4. fitting
5. attack
6. dataset

Have defined interfaces and do not communicate through local variables. This allows "probe-points" (pdb or jupyter) to tap in before or after these setup functions. I'm not sure interjection in those points is that compelling; it is easier to affect setup with
`config` than to monkeypatch in the middle.

The "optional" refactor allows not-yet-converted `scenarios/*.py` to work without modification. It will be non-optional once those
are converted.

Next step: refactoring metric/attack/predict block.

**Comment by mwartell** [comment]
I've subtasked this issue

- [ ] #1089 
- [ ] #1090
- [ ] #1091

**Comment by mwartell** [comment]
Issues #1089 and #1090 have likely been obsoleted by https://github.com/twosixlabs/armory/pull/1093/files

**Comment by davidslater** [comment]
Closing, as only #1091 remains, and that is tracked on a separate milestone.
