### ISSUE TITLE
Error loading MSCOCO baseline model in ART when using Numpy 1.20.1

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1055]
See [issue](https://github.com/Trusted-AI/adversarial-robustness-toolbox/issues/1092) in ART.

This affects both APRICOT and D-APRICOT baseline models. The published 0.13.0 TF1 image uses Numpy 1.19.2, whereas building locally with the latest on `dev` branch yields Numpy 1.20.1.

**Comment by ng390** [comment]
Fixed by #1056
