### ISSUE TITLE
Build interface for "range of epsilon" attacks

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1066]
The [SNR_PGDRange](https://github.com/twosixlabs/armory/blob/master/armory/art_experimental/attacks/snr_pgd.py#L12-L80) attack iterates over a range of epsilons. It would be useful to have a convenient interface for applying this kind of approach to any attack, in order to use a sole config to generate an epsilon vs. robustness curve. Plotting utility functions should also be provided to easily convert a results JSON into a useful visualization

**Comment by Embeddave** [comment]
No one asked me but would be nice to have the same kind of interface for number of iterations, cf. this paper
https://openaccess.thecvf.com/content_CVPR_2020/html/Dong_Benchmarking_Adversarial_Robustness_on_Image_Classification_CVPR_2020_paper.html

**Comment by lcadalzo** [comment]
Closed with #1071
