### ISSUE TITLE
OOM error ucf101 test with PGD Patch, PGD, Saliency attacks

### ISSUE THREAD

**Issue by richardkxu** [twosixlabs/armory#1094]
## Description

Hi, I have downloaded `armory v0.13.1` from github without modification and run it with `ART v1.6.2` and got OOM error at [this line](https://github.com/twosixlabs/armory/blob/deb7a469bf4a7497d14fdd87eba6417b5e44589f/armory/scenarios/video_ucf101_scenario.py#L198) on the 554/3783 video with size (1, 814, 240, 320, 3). I got OOM on PGD Patch, PGD, Saliency attacks. I have run both with and without docker, tried both `master` and `dev`, all OOM. I am using 2080Ti with 11 GB. A member from two six was able to reproduce the error on his side. 

## How to reproduce?
since by default, the test dataset has `shuffle_file=False`, you can simply reproduce the error by skipping the first 553 samples in `video_ucf101_scenario.py`:
```
for batch_idx, (x, y) in enumerate(tqdm(test_data, desc="Attack")):
    if batch_idx < 554:
        continue
```
noted that adding `"eval_split": "test[553:555]"` to dataset config will not get you the same video, likely due to `eval_split` mechanism shuffle the order somewhere.

## Possible causes
1. a few related github issues talked about memory leaks. However, this is unlikely the cause since I have not noticed cumulative increase in GPU memory. I got OOM even when just running on the 554th video.
    - https://github.com/twosixlabs/armory/issues/502
    - https://github.com/twosixlabs/armory/pull/637/commits/f1be1ad5cfdaa086b556a7fff2423e9825b9bd9a
    - https://github.com/twosixlabs/armory/issues/869
2. It is likely due to the fact that this video is too long (814 frames). setting `max_frames=512` still OOM. Also, the `batch_size=1` in `attack.generate` and `classifier.predict` does not help either since the batch dim is always 1 during ucf101 testing. we really want to put a batch size on the num_frames dim, but this will cause problem since we need to make predictions for all frames of the video and take the mean.
3. `fit_preprocessing_fn_numpy` at [this line](https://github.com/twosixlabs/armory/blob/deb7a469bf4a7497d14fdd87eba6417b5e44589f/armory/baseline_models/pytorch/ucf101_mars.py#L26) is not used during testing, which randomly pick 1 clip from each video. only `preprocessing_fn_torch` is called inside forward function. I guess this is somehow desirable, since we want to run inference on all frames during testing.

**Comment by davidslater** [comment]
There is now a max_frames argument in the data generator function that will clip videos before it reaches the model. This should fix the problem. Before, even with max_frames set, it still generated gradients back to the full input space, which is likely the cause of the OOM.

https://github.com/twosixlabs/armory/blob/develop/scenario_configs/ucf101_baseline_pretrained_targeted.json#L28

**Comment by davidslater** [comment]
There is now a max_frames argument in the data generator function that will clip videos before it reaches the model. This should fix the problem. Before, even with max_frames set, it still generated gradients back to the full input space, which is likely the cause of the OOM.

https://github.com/twosixlabs/armory/blob/develop/scenario_configs/ucf101_baseline_pretrained_targeted.json#L28
