### ISSUE TITLE
Are performers allowed to contribute ?

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [twosixlabs/armory#1103]
Hello,

I might have an improved(>40x speedup on a 3sec clip) version of the Kenansville attack. Is it something I could make a PR for ?

Best,

Guillaume

**Comment by GuillaumeLeclerc** [comment]
also @kevinmerchant @yusong-tan I think there might be an issue with the current implementation:

I believe that `dc_ind in x_psd_ind[:id]` should be replaced by `dc_ind <= id` no ?

Let's take the following example:
```
x_psd_ind = [1, 0, 4, 3, 2]
dc_ind = 2
```
If I understand the goal of this condition, we want to check if we are about to zero-out the 0Hz freq.

Now if we have `id = 2` then `x_psd_ind[:id] = [1, 0]`. Which means we are going to zero out the first bin. However `x_psd_ind[:id]` is False.

Did I misunderstand something or is it actually a bug ?

**Comment by davidslater** [comment]
Yes, feel free to make a PR targeting `dev` branch.

As for the latter questions, I'll let @kevinmerchant or @yusong-tan speak to them.

**Comment by kevinmerchant** [comment]
This does indeed look like a bug to me.  In particular, since `dc_ind = np.where(x_psd_ind == 0)[0][0]`, `dc_ind` is already an index into the `x_psd_ind` array, and should therefore be compared directly to `id` rather than `x_psd_ind[:id]`.  @yusong-tan can you confirm?

**Comment by yusong-tan** [comment]
@GuillaumeLeclerc  you are correct.

`dc_ind in x_psd_ind[:id]` should be replaced by either `dc_ind < id` or `0 in x_psd_ind[:id]`

The idea is that PSD has a negative and positive frequency, except at DC. We want to make sure we zero two bins for each non-zero frequency.

**Comment by GuillaumeLeclerc** [comment]
That's what I had in my implementation. I will PR with the optimized+fixed version then. I have done extensive testing for equivalence between the two implementation but assuming this was a bug in the first place. Glad to hear I don't have to redo my testing.

**Comment by davidslater** [comment]
If you have any tests that you can contribute, that would be helpful as well.

**Comment by GuillaumeLeclerc** [comment]
Glad it ended up being useful :smiley:
