### ISSUE TITLE
Export samples doesn't always output pkl file with y and y_pred

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1135]
Suppose you specify  `"export_samples": N` in the Armory scenario config, where `N` is some int. If `N` is > than the number of samples actually evaluated, the pkl isn't outputted because [this](https://github.com/twosixlabs/armory/blob/master/armory/utils/export.py#L46-L48) conditional block is never reached.

**Comment by swsuggs** [comment]
This got fixed in PR #1261
