### ISSUE TITLE
add more basic scenarios

### ISSUE THREAD

**Issue by priamai** [twosixlabs/armory#1140]
Hi there,
this project is awesome, I am wondering if would be possible to add more basic examples for people to get started such as the creditcard fraud example from [counterfit](https://github.com/Azure/counterfit/wiki/Tutorials).
Cheers.

**Comment by davidslater** [comment]
Hello! There has been growing interest for additional basic examples. We haven't added text-based or tabular data (as in creditcard fraud) before, which require different threat models in the input space, so those are less likely to be added in the next release, but something that is on the roadmap.
