### ISSUE TITLE
workflow improvement ideas culled from slack

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1142]
- [ ] when calculating the adversarial accuracy, it would be nice if stochastic models predicted the output multiple times that way we’d get less variance in the metric which would make it easier to see the impact of changing parameters if it’s just a small improvement. 

- [ ] it would be nice to run multiple attacks after training once (for the models where the weights are stochastic and the benign accuracy changes each run.)
what i’m currently doing in one of my (custom) scenarios is setting default attack parameters and then i’m doing a for loop of all the attacks where i reload the attack each time and i have a list of parameters that i’m changing and i just overwrite those parameters each time. note: this also requires updates to the metrics to allow for multiple attacks. currently, i’m just printing the results to the terminal.

- [ ] It would be nice if the cumulative adversarial success rate was shown at the end of every batch. (I'm assuming that those numbers are on-hand and just need to be printed?). That way, if I try to do a run with too many batches and it's taking forever, then I can still grab the results for a smaller sample. Also, if something isn't working at all, then I could just kill it and try something else.

- [ ] Treating an evaluation as a batch job as Armory hampers  understanding when the batch time is measured in days.

**Comment by davidslater** [comment]
Superseded by 
#1388
#1367 

For point 2 above, multiple attacks should really be handled separately and then collated. If training is involved, train and save off the model once, then run a suite of attacks as separate configs.
