### ISSUE TITLE
Update dev to ART 1.8

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1151]

**Comment by lcadalzo** [comment]
[This](https://github.com/Trusted-AI/adversarial-robustness-toolbox/tree/development_object_tracking_attack) ART branch is 1.8.1 + the `AdversarialTexturePyTorch` attack, and it's what we plan to pin to for the Armory 0.14 release.

**Comment by lcadalzo** [comment]
Closing due to #1181
