### ISSUE TITLE
deny acceptance of Dockerfiles in favor of container images

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1165]
This is mostly a documentation and communication task.

We need to inform participants that **if they must** they can submit a container image based on a Armory distribution image. 

We also need to educate the submitters that

1. dockerfiles are no longer accepted and that custom containers must have a blessed Armory base.
2. what circumstances could need a custom container and when that's not necessary

The submission ui might want to also contain this guidance.

**Comment by mwartell** [comment]
Per @davidslater (GARD Sync 8-Nov-21) it is reasonable to ask that performers submit an x86/linux container image along with the generating Dockerfile. 

We know we need them to start from a CUDA base, so I am proposing that submitted images must  be derived from TwoSix containers. The prescription could be: Dockerfile must begin with
```
FROM twosixarmory/pytorch:latest
```
(or `twosixarmory/tf1` or `twosixarmory/tf2`) as appropriate. Because the Armory docker images are derived from `nvidia/cuda:11.2.1-cudnn8-runtime-ubuntu20.04` this ensures (via transitivity) that the performer image derive from the nvidia base.

**Comment by davidslater** [comment]
Sometimes people need to use different versions of TF / Pytorch with other supporting packages, which makes it very hard to base off of our containers.

**Comment by mwartell** [comment]
Resolved in Slack:
> Container submissions should be derived FROM twosixarmory/framework. If a performer cannot work from the armory base, they must derive FROM nvidia/cuda:11.2.1-cudnn8-runtime-ubuntu20.04

**Comment by nsxfreddy** [comment]
What does "container submission" mean? Changing from submitting a Dockerfile to a container may impact our approval processes.

**Comment by mwartell** [comment]
Per the comments from @nsxfreddy and others, we cannot require images from performers, so this issue is closed.
