### ISSUE TITLE
numba library version conflict when ART is updated to 

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1183]
In PR #1181 adversarial-robustness-toolbox is moved from 1.6.2 to `development_object_tracking_attack`. This generates [the error report](https://github.com/twosixlabs/armory/runs/3932761083?check_suite_focus=true#step:4:2529)

    E   ImportError: Numba needs NumPy 1.20 or less

Following #1175 and #1180, the pytorch/Dockerfile should be reordered to put as much in conda first  as afforded by the conda repos.

**Comment by lcadalzo** [comment]
Closing due to #1181
