### ISSUE TITLE
Armory 0.14.0 host-requirements.txt duplicate dependencies

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#1205]
There appears to be some duplicate dependencies in `host-requirements.txt`. I assume we should choose the higher version, but probably worth documenting the correct choices:

https://github.com/twosixlabs/armory/blob/a5d2c29081e80ff5de5b9b2ee16fbefe903d5ae2/host-requirements.txt#L19
https://github.com/twosixlabs/armory/blob/a5d2c29081e80ff5de5b9b2ee16fbefe903d5ae2/host-requirements.txt#L30

**Comment by davidslater** [comment]
The dependencies are also out of date for some of them. Fixing...

**Comment by mwartell** [comment]
Fixed by cf6a5c614dfd2470e467a3408e0abaf63acd2453
