### ISSUE TITLE
Export bboxes as JSON

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#1268]
I noticed that there is an in-progress implementation of drawing bounding boxes on images in #1261. Would it be possible to support exporting the bounding box annotations as a JSON file? There is already a well-defined JSON results schema for COCO: https://cocodataset.org/#format-results. Using this schema will enable tools like [FiftyOne](https://voxel51.com/docs/fiftyone/) to load and annotate the images.

**Comment by lcadalzo** [comment]
Added in #1398
