### ISSUE TITLE
Refactor export sample feature

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1273]
Refactor export_sample feature:

- the inclusion of predicted/ground-truth boxes should be extended in a clean way to the generic object detection scenario (i.e. not just CARLA, xView too)
-  we will likely want to move the exporting code outside of `run_attack()` into its own scenario method
- the box plotting logic inside `export.py` should be cleaned up. Currently there are various kwargs that get passed around and used in unintuitive ways. See [this](https://github.com/twosixlabs/armory/pull/1261#discussion_r800842651) comment. This may entail having export functions (as well as `Context` classes) separated by scenario rather than data type (e.g. image classification and object detection use different functions)

**Comment by lcadalzo** [comment]
An additional reason for this refactor: currently, since exporting occurs inside the `run_attack()` method, if a user sets `export_samples` correctly in the config but then uses the `--skip-attack` flag, no samples will be exported nor will there be any warning message indicating this

**Comment by davidslater** [comment]
Fixed by #1297
