### ISSUE TITLE
Enable export samples to grab data after preprocessing steps are applied?

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1285]

**Comment by lcadalzo** [comment]
@davidslater could you elaborate on this one?

**Comment by davidslater** [comment]
This was recording a conversation we had earlier about folks that wanted to export samples after a preprocessing defense (I think primarily for CARLA scenarios).

My guess is that we punt on this for now, but reconsider it after the measurement update is done?

**Comment by lcadalzo** [comment]
Got it, I think this overlaps with what we're trying to accomplish with the measurement update so I agree it makes sense to wait for that.
