### ISSUE TITLE
Finalize deprecation of TF1

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1289]

**Comment by shenshaw26** [comment]
In order to finish this, we need to fix / remove this test `tests/test_tf1/test_tf1_models.py::test_tf1_mnist` and then we need to update CI to not use the old tf1 docker image.

**Comment by davidslater** [comment]
Other remaining steps:
- [ ] Remove tf1 from docker builds

**Comment by mwartell** [comment]
Fixed by https://github.com/twosixlabs/armory/issues/1289#:~:text=16%20days%20ago-,TF1%20deprecation%20%231290,-Merged and cf6a5c614dfd2470e467a3408e0abaf63acd2453
