### ISSUE TITLE
armory.scenarios.main' found in sys.modules after import of package

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1291]
/opt/conda/lib/python3.7/runpy.py:125: RuntimeWarning: 'armory.scenarios.main' found in sys.modules after import of package 'armory.scenarios', but prior to execution of 'armory.scenarios.main'; this may result in unpredictable behaviour
warn(RuntimeWarning(msg))

I've removed much irrelevance from this issue. This is the warning that I think should be hunted down and killed.

**Comment by mwartell** [comment]
I have seen this through the logging-improvements #1271 development and cannot explain it.

**Comment by davidslater** [comment]
I don't think that it is related to the RuntimeWarning. That has been there for a long time. I think I ran into the error there due to my config directory being messed up.

**Comment by davidslater** [comment]
I do agree that this is something we should hunt down and remove, though.

**Comment by davidslater** [comment]
Fixed by #1292
