### ISSUE TITLE
Merge poisoning branch into develop

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1298]

**Comment by reed-twosixlabs** [comment]
Will negate the SPD computation before this PR happens.

**Comment by davidslater** [comment]
@reed-twosixlabs has the SPD computation been negated? Or does a fix for that need to happen?

**Comment by reed-twosixlabs** [comment]
Yes, this has been fixed.

**Comment by davidslater** [comment]
Great, closing issue.
