### ISSUE TITLE
docker copy syntax error

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1301]
Docker complains

	When using COPY with more than one source file, the destination must be a directory and end with a / or a \

Better perhaps is to use an explicit destination path.

this is with Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

**Comment by davidslater** [comment]
So we'll just need to be careful to add things into the dockerfile if we add any additional top level files or folders?

**Comment by mwartell** [comment]
It is a docker syntax corner-case that isn't likely to bite again and the diagnostic message is clear. This should have been closed.
