### ISSUE TITLE
Pin end-to-end tests and computational requirements to armory outputs?

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1310]
(@shenshaw26, this may be related to your thoughts/discussion on resource requirements, but is broader.)

My thought is that for end-to-end testing, we run the scenarios (with some subset of samples) and record all of the relevant metrics (including computational metrics) in a new top-level `results` directory. We manually inspect them to ensure that we are getting what we want. Then...

These can then a) can provide proof of computational resources, b) task performance numbers for statistical checks, c) results that can be directly mapped to from the docs (instead of the possibility of drift between the two), and d) demonstrate the results output format.

**Comment by shenshaw26** [comment]
This sounds good to me, a few comments:

- When you say "the scenarios" do you have a specific set in mind?  
- Can you list the "relevant" metrics that we would be interested in? ( I can think of some, but I think we should outline them here to be specific)
- What does "some subset of samples" actually mean?  Will that be a random choice at runtime or will we create new datasets (or appropriate slices) to make sure its repeatable? I imagine this choice will have some interplay with the choice of "metrics" above so it would probably be nice to be specific here.
- what does "top-level `results`" directory mean?  Do you mean something in `~/.armory/` If so, how does that interplay with `outputs/` directory?
- Seems like we need some decisions about "what we support".  For example should all scenarios be able to be run solely on CPU?  Should all scenarios be able to run with a GPU?  If so, do we have specific types that we say we support or specific resource minimums?  Should all scenarios be tested in a `native` (aka no-docker) environment as well as in `docker` containers?  Do we know which scenarios should map to which containers (I think the answer is yes, but just trying to be verbose here)?

Overall this is right in line with the question I was asking about resource requirements

**Comment by shenshaw26** [comment]
On Containerization:   

- I am still not sure I am clear as to what we are trying to achieve with the armory containerization bits.  For example, why don't we just let `armory` be the execution engine such that `armory run ...` executes all things in the native environment and, then, if a person desires to use a docker container they can simply call `docker run -it [container] ... armory run ....`.  It seems like that are a variety of ways one might want to run armory inside docker (e.g. mount external drives for storage vs keep it all completed contained in container) and its a lot of code maintainence / support to try to cover these bits.  
- It seems like there is some machinery in armory pointing to an approach where armory would manage multiple armory instances in parallel...is that something we actually support?  If so, do we really need to do that? If it is a real requirement, we should use some sort of orchestration layer on top of docker (e.g. kube, mesos, etc.) to make this happen....am I missing something?
- What is the level of use around the various armory execution modes (e.g. armory exec, --interactive, etc.)?  In my very short time here, I have really only seen people use `armory run thing.json` and if that is all that is used, we could drastically simplify the codebase which would make it much easier to maintain.  Also, FWIW, many of these things feel like they just belong in docs for how to do things in docker.

**Comment by davidslater** [comment]
Regarding specific scenarios, I did not have a specific set in mind - but potentially all of the ones we provide configs for. I do not see this "results" directory as being connected to the `outputs` directory in armory config. It might actually make more sense to have it be a subdirectory of your envisioned `experiments` directory. That would make it clear that they result from running those configs.

For relevant metrics: these depend on task, but yes, could write them out on a per-case basis.

I like being able to run all of our built-in scenarios, at least in theory, on CPU. However, this always causes a significant computational overhead, so it's preferred to use GPU. The resource minimums are very much dependent on model size and (to a lesser degree) on dataset size and attack. For mapping containers to scenarios, it is not necessarily one-to-one. For many of the scenarios, both the pytorch and tf containers will work (if using the corresponding model).

**Comment by davidslater** [comment]
Regarding containerization:
1) Portability/replicability/integration. For the program, it is extremely important that we can replicate all that is being done with a defensive technique. Once we start adding a lot of docker connections that we don't have control over, it becomes much harder to validate/verify what has been done on their end. In my experience, usage of `native` mode has been rare (mainly due to folks who can't install docker), so it doesn't make sense to me to default to that. I do think it would be good to enable the default environment mode to be configurable so that people don't have to pass kwargs all the time for that, though.

2) The multiple armory instances functionality can be dropped. Typically, we do parallelization with separate armory run commands, and an orchestrator that does this parallelization and then collates results should probably be separate from the core codebase.

I use `--interactive` mode pretty extensively. I think Lucas does as well. It's very helpful for setting break points, debugging issues, more quickly iterating, etc. For `exec` mode, I only occasionally use that, but it's almost identical to what `launch --interactive` is doing. The `--jupyter` mode sees less use, but is also one of the more requested modes, so I would like to expand usage of that.

**Comment by davidslater** [comment]
From above, on "some subset of samples", I would just use the first 10 or 100 samples (depending on computation time) of a specific data split (typically "test") with file shuffling off to ensure replicability (I think shuffling is off by default).
