### ISSUE TITLE
Consider the local development process with docker containers in the new versioning system

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1320]
With the new versioning system, the version will change when a commit is made. If you make a commit and then launch a scenario, it will error because there isn't a docker container for it.  It seems onerous to me to rebuild the docker image (even if it is only the last couple of layers / armory install) each time I locally add a commit. On the other hand, I would guess that 99% of the time if I simply used the previous docker image and ran from the armory directory, it would be fine. I would certainly want the CI test to build a new container, but not something I want to do every time I commit something.

Thoughts?

**Comment by davidslater** [comment]
One caveat about Matt's 2. ^^ is that if you are running `armory` from somewhere else, it won't overwrite that code.

**Comment by davidslater** [comment]
Since we're using the git tree for versioning, one solution is to traverse the tree until you hit a version tag or dev docker container. This would be a relatively simple comparison of `docker images` and `git log`.

Then, if you need a new container for some reason (e.g., new ART patch), you do a simple `python docker/build.py pytorch`, it tags it appropriately with the short SCM tag, and you're good to go.

**Comment by davidslater** [comment]
A workaround for docker images could simply be to completely specify the container version you are using (not my favorite solution).

**Comment by davidslater** [comment]
Another (complimentary) solution that would be helpful for both `armory` and `art` would be to enable local copies of those libraries to be mapped into `/workspace/(art|armory)/` as a config parameter so that they take precedence on the python path and enable `armory` to be invoked from anywhere on the host system.

To prevent weird name conflicts/overwrites, we could then restructure /workspace/ to be:
```
/
    workspace/
        armory/
        art/
        host_cwd/
```

**Comment by mwartell** [comment]
I like this. Having any program change its behavior based on where you run it is confusing. Explicit is better than implicit, as they say.

> Another (complimentary) solution that would be helpful for both `armory` and `art` would be to enable local copies of those libraries to be mapped into `/workspace/(art|armory)/` as a config parameter so that they take precedence on the python path and enable `armory` to be invoked from anywhere on the host system.

I'm thinking perhaps `--armory-local=~/armory` and `--art-local=~/git/art`. While these would be a pain for us the most avid armory users, Seth and I have been expecting to augment ~/.armory/config whereby these items could be set per user.  Also a part of this would  be `--use-config=~/.different-armory` and `export ARMORY_CONFIG=~/.different-armory` 

I'm not wedded to any of those option names.

**Comment by davidslater** [comment]
We could extend `armory configure` with `armory configure --dev` to add those additional items

**Comment by christopherwoodall** [comment]
> I'm thinking perhaps --armory-local=~/armory and --art-local=~/git/art.

I like the idea of being able to mount different "vendor'd" tools as volumes; e.g. `docker run ... -v ~/art-dev:/app/vendor/art`.

The only modifications I foresee are to the Dockerfile; e.g. creating the vendor directory for those libraries, either using `--prefix` with pip or `config --add` with conda , then adding `VOLUME ["/app/vendor/tool1", "/app/vendor/tool1"] to the build.


As for the container versioning, the easiest solution I've found is retagging the latest to [match my branch](https://github.com/christopherwoodall/armory/blob/pep-0518-pyproject.toml/tools/bin/hacking.setup.sh). 

What solutions are people currently utilizing to get around this?
