### ISSUE TITLE
Some sort of versioning for base image?

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1324]
If we produce a new base image and tag it as "latest", and the changes are not backwards compatible, then branches not yet synced to that may fail.

**Comment by davidslater** [comment]
Perhaps we just do this according to minor release? E.g., `twosixarmory/base:0.15`.

**Comment by mwartell** [comment]
We discussed this some today. I think we agreed that monotonic version numbers were likely sufficient. That is, the first base was tagged 1.0.0 and the next should be 2.0.0. I don't see strong cause to drop the minor and patch numbers even if they are always zero.

We also bounced around three distinct uses:
1. the user truly doesn't care whereby `latest` should be preferred
2. a developer needs a new base (e.g. 2.0.0) which would break Works In Progress 
3. the new base has reached fixation and should be used everything going forward.

I think cases 1 & 3 are the steady state while (2) only obtains for a short period. I suggest that we code for the typical case (1 and 3) and use the `docker/build.py --base-tag=2.0.0` escape for the (2) case.  But this would entail a three step action that would likely get forgotten:
1. build and push twosixarmory/base:2.0.0
2. wait for fixation to occur (how do we know?)
3. tag base:2.0.0 as latest

I'm not sure there is an obviously correct answer to this.

**Comment by mwartell** [comment]
"There are only two hard things in Computer Science: cache invalidation and naming things."
-- [Phil Karlton](https://martinfowler.com/bliki/TwoHardThings.html)

"And this issue has both"
-- me

**Comment by davidslater** [comment]
I had another thought on naming convention for the base - let's number it in a way that is at least (partially) replicable. If we name it based on the armory version that generated it, then it becomes a little easier to reason over things like regression bugs. (Otherwise, I guess we just directly inspect the base image layers?)

**Comment by davidslater** [comment]
Regarding the use cases ^^ above:
> We also bounced around three distinct uses:
> 1. the user truly doesn't care whereby `latest` should be preferred
If we are just building images off of the base, this is likely still a developer, not an end user. I think for the standard case, simply running `python docker/build.py <framework>` without built-tag args should be fine. Whether its `latest` or a specific tag, we want this to be default.
> 2. a developer needs a new base (e.g. 2.0.0) which would break Works In Progress
This will happen whenever our dependencies have non-backwards compatible changes.
> 3. the new base has reached fixation and should be used everything going forward.
I think that if we have maintenance release branches, those should be allowed to live on the old base. Changes to the base could affect downstream user code even if it doesn't directly cause bugs in armory. As there could be considerable time overlap between old maintenance releases and most recent releases, I think that it be a serious time lag before the new base should be used on everything going forward.

I would add another use case:
4. User needs to create a custom docker image that cannot be easily based off of one of our release images (i.e., they need to start at base). For those individuals, it would be helpful that they can count on a stable base image.

**Comment by davidslater** [comment]
We will keep 2 different versions for the base image, in line with current `docker/build-base.sh`.

One will be the pin of the current version. This can be used to refer back to older bases for use cases 2 and 4. The other is the "latest" tag, which will generally be preferred.
