### ISSUE TITLE
validate that python 3.9+ can run amory

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1342]
This would reduce our test space to 3.7 and 3.8. (Also, we should probably expand the matrix to include both supported versions?)

**Comment by shenshaw26** [comment]
This makes sense to me.  Is there a reason why we are not explicitly supporting 3.9 (it is almost 2 years old now)?

**Comment by davidslater** [comment]
I think that this is due to some of our dependencies not working with 3.9. However, we haven't really tested.

I'm thinking:
A) remove explicit support for python 3.6 (including badge on our landing page)
B) add 3.8 to the test matrix (at least for the non-docker tests)
C) see if adding 3.9 to the test matrix causes failures (if it does, document and remove)

Three major questions:
1) What to do about the docker testing? Keep in 3.8 in the images and only publish images with 3.8 (seems simplest to me). Then our primary testing of multiple python versions is in the native tests. If that provides reasonable coverage, I think that's fine.
2) Do we need to matrix across os and python version? Could we test on macos for one version and then just use ubuntu for multiple versions?
3) What impact will expanding the python version test matrix have on CI test time?

**Comment by christopherwoodall** [comment]
There's still a lot to do, but I think we can call this issue closed? Thoughts @mwartell  @davidslater 


## Proposed Fixes [[PR](https://github.com/twosixlabs/armory/pull/1614)]

- [x] [Remove Python 3.6 badge](https://github.com/christopherwoodall/armory/commit/04a406c7688331d8d3a994b1f8028b4ca84f3938) from landing page. 

- [x] [Python 3.10, and Ubuntu 22.04](https://github.com/christopherwoodall/armory/commit/74f05955ce97ce6b8290eeedab9c6b9f16a794d3) added to tests.

- [x] [Updated](https://github.com/christopherwoodall/armory/blob/1342-validate-that-python-39%2B-can-run-amory/host-requirements.txt) out of date pinned dependencies. Would like to add that into the CI pipeline eventually.

- [x] [Temporary work around](https://github.com/christopherwoodall/armory/blob/bf92abb1bbb593f39a9049fc8968356c71520e80/setup.py) to fix SCM errors when building containers with the Github Workflow; image attached.

- [x] Started work improving the current [`docker build` tests.](https://github.com/twosixlabs/armory/pull/1614/commits/8cd26945c3d3ce155f8fc8ca9ae067f128e92d4d) They fail for a different reason now; see image 2.


## Attachments
**IMAGE 1**
![image](https://user-images.githubusercontent.com/363708/190024664-58f338fa-5661-468a-8668-982a4a18be55.png)

**IMAGE 2**
![image](https://user-images.githubusercontent.com/363708/190042010-3bff5978-258a-4217-a63d-cbdb6eb84638.png)
