### ISSUE TITLE
SCM Versioning - Armory fails when using code snapshots

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1369]
One side effect of the SCM versioning method in develop is that armory must either be pip installed or be in a valid git repo in order to be used.

Snapshots from tags, such as https://github.com/twosixlabs/armory/tags, will fail. Armory cannot be imported from them and it also cannot be pip installed from them.

To replicate, download a snapshot of the develop branch: https://github.com/twosixlabs/armory/archive/refs/heads/develop.zip
Then:
```
cd armory-develop
pip install -r requirements.txt  # this will work
pip install -e .  # this will fail 
python setup.py --version # this will fail
python -m armory  # this will fail
python
>>> import armory  # this will fail
```
They all fail due to `python setup.py --version` failing. And since this happens in `armory/__init__.py`, it causes everything in the library to fail.

Is this also why we need to send an SETUPTOOLS_SCM_PRETEND_VERSION into the container when pip installing?

**Comment by shenshaw26** [comment]
Yes, this is expected and is why we need `SETUPTOOLS_SCM_PRETEND_VERSION`.  Is this a common use case?  If so, maybe we need to consider an alternative in `__init__.py` where it defaults to version=UNKNOWN or something.  This would still allow the overrides but also allow use of armory even when it is not installed.  

Just to try to keep my mind clear about use-cases, its seems I am tracking the following:
- Run Armory locally with pip installed, using wheel from pypi
- run armory locally with/without pip installed from git clone
- run armory locally with/without pip installed from snapshot
- run armory within docker container where armory is prebuilt inside the container
- run armory within docker container where armory-dir is mounted into container and then overrides the pre-built version (not sure if this needs to support both pip installed of mounted drive or can just be run at repo root)
- others?

**Comment by shenshaw26** [comment]
@davidslater @mwartell , In poking at this a bit more, its unclear to me how all the different combinations should behave.  For example, for the simple cases we have:

| armory on PYTHON_PATH | armory pip installed | Expected Result |
|-----------------------|----------------------|-----------------|
| No | No | Should NOT work <br> ModuleNotFoundError: No module named 'armory'|
| No | Yes | should work <br> `__version__ = importlib.metadata.version("armory-testbed")` |

which makes sense.  However when you get to the more complicated cases (e.g. armory src on PYTHON_PATH) I am not sure what should happen:

| armory on PYTHON_PATH | armory pip installed | Expected Result |
|-----------------------|----------------------|-----------------|
| Yes <br> setup.py available  <br> .git = all history available | No | should work <br> `__version__ = $(python setup.py –version)`|
| Yes <br> setup.py available  <br> .git = only HEAD | No | ??? |
| Yes <br> setup.py available  <br>  no .git | No | ??? |
| Yes <br> setup.py NOT available  | No | ??? |
| Yes <br> (*consider all perms above*)  | Yes | ??? |

For the `???` rows above, if we can make a decision, I am happy to implement.

**Comment by davidslater** [comment]
For columns 1 and 2, are we talking about the same armory? (I.e., we're _not_ talking about one version pip installed and a different version on PYTHON_PATH)

**Comment by davidslater** [comment]
For rows 2-5, I think that "UNSUPPORTED" is fine for all of them.

**Comment by davidslater** [comment]
Maybe something like:
```
def get_version():                                                                       
    try:                                                                                 
        return importlib.metadata.version("armory-testbed")                              
    except:                                                                              
        pass                                                                             
                                                                                         
    try:                                                                                 
        return subprocess.call("$(python setup.py –version)")                            
    except:                                                                              
        pass                                                                             
                                                                                         
    return "UNSUPPORTED"                                                                 
                                                                                         
__version__ = get_version()                                                              
__version__ = re.sub(r"dev\d+\+(g[0-9a-f]+)(\.d\d+)?$", r"\1", __version__)
```

**Comment by mwartell** [comment]
David's proposed code ☝️  has the advantage of being comprehensible and explainable.

**Comment by davidslater** [comment]
If `setup.py` and `importlib` disagree, what do we do?
```
(armory-py310) √ david.slater@mac0909:~/armory% python
Python 3.10.3 (main, Mar 28 2022, 04:26:28) [Clang 12.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib import metadata
>>> metadata.version("armory-testbed")
'0.14.5.dev31+g0cc88fc'
>>> exit()
(armory-py310) √ david.slater@mac0909:~/armory% python setup.py --version
0.14.7.dev119+gc0f5b11.d20220328185643
```

**Comment by davidslater** [comment]
^^ I may have just found a dumb edge we should probably ignore.

**Comment by davidslater** [comment]
So calling `importlib` first would effectively break versioning scheme in dev repos.

**Comment by davidslater** [comment]
Is there a way for metadata to determine whether armory has been installed in editable mode?

**Comment by shenshaw26** [comment]
Not a great one: https://stackoverflow.com/questions/43348746/how-to-detect-if-module-is-installed-in-editable-mode

**Comment by davidslater** [comment]
Is there a way to tell if it has been installed via PyPI? How is the version shipped with that?

I would like to avoid the overhead of `python setup.py --install` whenever armory is loaded, especially for folks who pip install from PyPI or use our containers.

**Comment by mwartell** [comment]
The PyPI releases should all have three number semver like 0.15.1.  Or, conversely, we ought never post a 0.15.1.g123456 wheel or sdist.

**Comment by davidslater** [comment]
I mean, how is that incorporated in the package? (I.e., it doesn't package the full git clone, right?)

**Comment by shenshaw26** [comment]
In testing another ticket, I found this to be a bit interesting...
```
#23 1.715 Building wheels for collected packages: armory-testbed
#23 1.715   Building wheel for armory-testbed (setup.py): started
#23 2.321   Building wheel for armory-testbed (setup.py): finished with status 'done'
#23 2.324   Created wheel for armory-testbed: filename=armory_testbed-0.14.7.g6d9be95-py3-none-any.whl size=448799 sha256=d707f00dc5f7442a9b8b58e880e9ba35b3702b335b3b812d789cdc20df0f9e9d
#23 2.324   Stored in directory: /tmp/pip-ephem-wheel-cache-wgnrikhw/wheels/bc/ea/3e/2152800ddceb197496010262afcd12f0131a1579176f195931
#23 2.328   WARNING: Built wheel for armory-testbed is invalid: Metadata 1.2 mandates PEP 440 version, but '0.14.7.g6d9be95' is not
#23 2.328 Failed to build armory-testbed
#23 3.118 Installing collected packages: armory-testbed
#23 3.120     Running setup.py install for armory-testbed: started
#23 3.730     Running setup.py install for armory-testbed: finished with status 'done'
#23 3.738   DEPRECATION: armory-testbed was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
#23 3.802 Successfully installed armory-testbed-0.14.7.g6d9be95
#23 3.802 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#23 DONE 4.0s
```

I wonder if we need to revisit our versioning schema @davidslater  @mwartell ??

**Comment by shenshaw26** [comment]
> I mean, how is that incorporated in the package? (I.e., it doesn't package the full git clone, right?)

I don't really know the full details of how the package gets built or its contents...but I can look into it.  I was looking at the release.yml and it seems that we package using bdist_wheel....so I can take a look at that and see what gets put into the build.

**Comment by davidslater** [comment]
It may actually be a good thing that we can't build a wheel for our armory-testbed-0.14.7.g6d9be95 versioning system - that ensures that we can only push properly tagged versions.

**Comment by davidslater** [comment]
Using SCM, our full version looks like `0.14.7.dev370+gd45e6707.d20220428170524`. However, we trimmed this down to the hash, resulting in `0.14.7.gd45e6707`.

One issue with direct usage (other than being long and ugly) is that
`twosixarmory/pytorch:0.14.5.dev370+gd45e6707.d20220428170654`
is not a valid docker tag due to the `+` symbol.

**Comment by davidslater** [comment]
Now that `__version__` is retrieved dynamically, having a working version is unneeded for direct import of armory. It will raise an error and log `"armory package is not pip installed and not locally cloned"` if a user attempts to get the version, which I think is more desirable than "UNSUPPORTED". It also has the local clone take precedence over pip install, when avaialable.
