### ISSUE TITLE
Integration of CIFAR10 for poisoning for Eval 5

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1372]
Moving from RESISC10 to CIFAR10

**Comment by swsuggs** [comment]
To compute the fairness metrics developed in eval 4, we need a Cifar10 explanatory model to do the silhouette analysis on.  tagging @yusong-tan and @Nathalie-B for awareness

**Comment by spolavar** [comment]
@swsuggs just want to confirm this task requires to train BEAN regularized model on CIFAR10 and provide you with the pretrained pytorch model. Correct? I'd be needing CIFAR10 dataset for that, I thought you'd mentioned that CIFAR10 is already integrated into armory. Can you please point me to it? Thanks! 
@yusong-tan

**Comment by yusong-tan** [comment]
Dev trigger and associated config added to PR #1443

**Comment by lcadalzo** [comment]
@swsuggs I'm closing after the merge of #1403. Please re-open if there are any other TODO's for CIFAR10 poisoning that we should be tracking prior to the release
