### ISSUE TITLE
Updated Threat Model for LibriSpeech ASR - Eval 5

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1373]
Currently, we just point to a list of transcripts and try to minimize targeted attack WER.

New (potential) material:
        phrase A to phrase A' (change sentence semantics, etc.)
        Entailment attack (measure of two sentences - whether they have same meaning, different, or neural)
        BERT score models
        Breakdown of WER for insertion, deletion, substitution

**Comment by lcadalzo** [comment]
From @yusong-tan : 
- "I only made target phrases for the first 100 audio clips, so we should restrict the scenario to no more than 100 examples."
- "Instead of selecting target phrase of similar length to the ground truth phrase, we'll need to pick target phrase based on input index"
