### ISSUE TITLE
Update Eval5 Configs -- Reorganize scenario_configs/ with subdirectories for each scenario

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1374]
Overview of Eval5 changes.
    CARLA -> high definition textures, more color
        new datasets
    Attacks - adopting new adversarial patch attack (PyTorch version in 1.10)
        Early version of depth attack (3x faster than current)
    Video tracking - upgrading dataset
        New adversarial texture attack
    Audio: phrase A to phrase B (totally different)
        phrase A to phrase A' (change sentence semantics, etc.)
        Entailment attack (measure of two sentences - whether they have same meaning, different, or neural)
        BERT score models
    Poisoning - adding witches brew; talk about logistics
        Added metric for poisoning
        One metric is only collected for filtering defenses
            *Add metric to all defenses
        Remove RESISC10, Add CIFAR10

**Comment by lcadalzo** [comment]
Configs should be updated to use newly received Eval 5 model weights files, which we have yet to receive

**Comment by lcadalzo** [comment]
Reorganize `scenario_configs/` in such a manner:

```
scenario_configs/
    eval5/
         carla_object_detection/
         carla_video_tracking/
         ...

    previous_evals/
        ...

```

Note that there may be a better name than `previous_evals`, but the intention is to separate eval5 out

**Comment by davidslater** [comment]
We can have standard configs in the root of this directory, but slimming this down considerably (to 1 or 2 per scenario file) would be great.

**Comment by davidslater** [comment]
I made a `eval1-4` subdirectory instead of `previous_evals`. I plan to push most of the old (audio-related) jsons there in my PR and leave ~1 config per scenario in the root.
