### ISSUE TITLE
Incorporate new metrics for poisoning - Eval 5

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1379]
Needs more info

**Comment by Nathalie-B** [comment]
@davidslater
Metrics should include: 
- In the fairness section: 
   1. Add samples per class
   2. Accuracy per class
- For filtering defenses: 
   1. Percentage of filtered data by the defense 
   2. Number of samples filtered 
   2. Percentage of filtered data that was not poison

**Comment by Nathalie-B** [comment]
P.S. this is in addition to all the dev. metrics already implemented for Eval 4

**Comment by swsuggs** [comment]
Completed in #1393
