### ISSUE TITLE
Update black to 22.3

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1382]
Black is now stable: https://black.readthedocs.io/en/stable/

Shortly before the version 0.15.0 release, we will update black to 22.* in test-requirements.txt as so:
```
black~=22.0
```

This will ensure that we stay on the latest part of 22, but won't migrate to 23 except explicitly. (See: https://black.readthedocs.io/en/latest/the_black_code_style/index.html#stability-policy)

**Comment by mwartell** [comment]
There is an implementation of this fix in #1383 which we should hold until closer to release time.
