### ISSUE TITLE
Consider refactoring armory into namespace subpackages

### ISSUE THREAD

**Issue by shenshaw26** [twosixlabs/armory#1384]
In recent discussions, the concept has come up that `armory` should, possibly, be refactored into a `namespace_packages` approach where their could be different subpackages under the common `armory` namespace.  

Cases for this are:
 - Separating armory into a `launcher` and `engine` where:
     -  the launcher is responsible for managing environment and compute resources and launching the `armory engine` in said environment
     - the `engine` is responsible for executing the evaluation "experiment" (akin to `python -m armory.scenarios.main` bits)
 - Separating the construction / deployment of `datasets` from the utilization of said datasets

## Approaches:
The python docs suggest 3 ways to accomplish this:

1. `native` mode - https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages
2. `pkg-util` mode - https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages
3. `pkg-resources` mode - https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages

## Documentation on apporaches:
https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages

Example `pkg-util` approach (probably best?):  https://github.com/pypa/sample-namespace-packages/tree/master/pkgutil

**Comment by shenshaw26** [comment]
@mwartell ^^^ I was thinking about using the `pkg-util` approach above....let me know your thoughts.

**Comment by mwartell** [comment]
As of 9ca07ad121931453f9ff03a6ee09efd7d934b654 setup.cfg is using the `package = find_namespace:` invocation with the new `launcher` directory which is peer to `armory`.  I think that means we're using the namespace approach.
