### ISSUE TITLE
Update Evaluation Configs - Attack Suites

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1391]

**Comment by mwartell** [comment]
I think this issue is in service of the upgrading the naive attack suites within sabot to match the ART release in #1523.  The relevant files are in https://github.com/twosixlabs/sabot/tree/master/sabot/jobs/test_plan

**Comment by davidslater** [comment]
As well as any scenario updates from MITRE.

**Comment by mwartell** [comment]
Look in armory/scenario_configs/eval5 and for new tasks
