### ISSUE TITLE
object tracking success rate metric

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1405]
USCI proposed a metric to better assess the single object tracking scenario. It involves calculating average IoU for a range of IoU thresholds. This is similar to mAP for object detection. Their description can be found in their Eval4 submission (USCI_CARLA_video_tracking GARD Evaluation 4 Submission Documentation.docx). It would be good to include in Armory, if possible.

**Comment by swsuggs** [comment]
completed by #1408
