### ISSUE TITLE
allow pytest to check warnings

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1414]
We want to have a pytest test check if a warning were omitted. There are two ways to accomplish this:
1. adapt the pytest caplog fixture to see loguru messages
2. use `warnings.warn` in the application and instruct loguru to pick up those messages

Updating caplog allows tests to be written like
```
def test_baz(caplog):
    func_under_test()
    for record in caplog.records:
        assert record.levelname != "CRITICAL"
    assert "wally" not in caplog.text
```
This mechanism is pretty close to grepping through the logs for `"wally"` which is slightly kludgy.  There is a code snippet which allows [pytest to access loguru messages in the loguru documentation](https://loguru.readthedocs.io/en/stable/resources/migration.html#making-things-work-with-pytest-and-caplog). The advantage of this mechanism is that it allows our typical `armory.logs.log.warning()` calls to be caught, so no changes to coding practice are needed.

There is the python standard [`warnings` module](https://docs.python.org/3/library/warnings.html) which uses the exception mechanism for warning notifications.  The main advantage is that it makes the pytest code cleaner as shown in the [pytest warnings docs](https://docs.pytest.org/en/6.2.x/warnings.html#warns).  This does introduce a new mechanism to the application code with its own peculiar semantics.  If desired, the [code to adapt warnings to loguru is available](https://loguru.readthedocs.io/en/stable/resources/recipes.html#capturing-standard-stdout-stderr-and-warnings).  We might want to do that anyway.

**Comment by davidslater** [comment]
I think for now, let's do the `caplog` approach, and then consider moving to warnings in a later release.
