### ISSUE TITLE
CI Test - Why isn't there an error?

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1434]
From #1432

Matt:
"This most recent fix works, but it doesn't make sense. The failure was because armory --version in the ci_test.yml was giving a bad version ("0.1") instead of "0.14.7.ge01675f" as was being built.

The fix for this is pretty standard with setuptools_scm. By default actions/checkout in an Action does a shallow clone at depth=1 of the repo which defeats the tag chasing code in scm. Setting that job to checkout the whole tree (fetch-depth: 0) clears the problem.

The thing I don't understand is why the pytorch and pytorch-deepspeech stanzas above and below the docker-tf2-unit step do not do a full checkout but work. I'd like @shenshaw26 to take a look at ci_test.yml to see if he groks why they are different."

**Comment by shenshaw26** [comment]
So I don't see an error here: https://github.com/twosixlabs/armory/runs/6196743409?check_suite_focus=true. 

Maybe there was something else going on?  But when I remove the fetch-depth, all tests pass.

https://github.com/twosixlabs/armory/pull/1446

**Comment by davidslater** [comment]
The error was here: https://github.com/twosixlabs/armory/runs/6133770969?check_suite_focus=true

**Comment by davidslater** [comment]
Looking at recent runs, however, it looks like all of the docker images are misnamed in CI due to the armory version being wrong. It just isn't causing errors:

https://github.com/twosixlabs/armory/runs/6196980856?check_suite_focus=true#step:4:468

**Comment by shenshaw26** [comment]
> The error was here: https://github.com/twosixlabs/armory/runs/6133770969?check_suite_focus=true

Yeah that one seems like it choked on not finding tensorflow=2.8
```
#11 [armory-base 7/8] RUN /opt/conda/bin/pip install --no-cache-dir     tf-models-official==2.8
#11 sha256:26a56dba818e400315195cc5e5750788460a9d9a81511e101fcdbfe9678ecc4f
#11 1.124 ERROR: Could not find a version that satisfies the requirement tf-models-official==2.8 (from versions: 0.0.1.dev0, 0.0.2.dev0, 0.0.3.dev0, 0.0.3.dev1, 2.1.0.dev1, 2.1.0.dev2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.4.0, 2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.7.0)
#11 1.124 ERROR: No matching distribution found for tf-models-official==2.8
#11 ERROR: executor failed running [/bin/sh -c /opt/conda/bin/pip install --no-cache-dir     tf-models-official==2.8]: exit code: 1
------
 > [armory-base 7/8] RUN /opt/conda/bin/pip install --no-cache-dir     tf-models-official==2.8:
------
```

Not sure what happened there...but you agree that there are no errors....so I think we can just merge the PR and then close this issue.
