### ISSUE TITLE
Review Documentation

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1454]

**Comment by lcadalzo** [comment]
This would've fit better in the review of the measurement PR but:

In the poisoning scenario code, I see the `hub.record()` method being used. However, I don't see anything in the metrics docs on this method and when to use it

**Comment by lcadalzo** [comment]
Is [this](https://github.com/twosixlabs/armory/blob/develop/docs/external_repos.md#custom-python-paths) hack still relevant and/or advised?

**Comment by davidslater** [comment]
Let's keep the hack in for now, until we update the docker image internal structure. We should really just update the config to enable different paths, but I don't think that works for external git repos at present.

**Comment by davidslater** [comment]
I will go ahead and update the docs on `hub.record()`
