### ISSUE TITLE
Separate CARLA dev and test preprocessing

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1460]
Since the new dev set is of a different shape than the test set, these 2 datasets should have different preprocessing functions at least until we receive the new test set.

When trying to `get_batch()` from the test set, this is the error you'll get:

```
ValueError: shape (1, 600, 800, 3) does not match shape (None, 960, 1280, 3)

```

Note: this applies to both object detection and video tracking datasets

**Comment by swsuggs** [comment]
Fixed in #1463
