### ISSUE TITLE
Run all configs with --check run before Eval 5 release

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1464]

**Comment by lcadalzo** [comment]
Just kicked off the batch of runs

**Comment by lcadalzo** [comment]
I've now added issues for each error I encountered. All errors, excluding a couple we were already tracking, were for `eval1-4` scenarios

**Comment by davidslater** [comment]
Looks good. I am fine with the errors being fixed (or configs deleted) in a patch release.
