### ISSUE TITLE
Bounding box format is wrong in `kwcoco_annotations_without_patch_and_sans_tiny_objects.json`

### ISSUE THREAD

**Issue by mzweilin** [twosixlabs/armory#1491]
I downloaded the `carla_od_dev_2.0.0` dataset from 

```bash
wget https://armory-public-data.s3.us-east-2.amazonaws.com/carla/carla_od_dev_2.0.0.tar.gz
```

and I found that the bbox format in `dev/_out/kwcoco_annotations_without_patch_and_sans_tiny_objects.json` does not conform with COCO. 

COCO assumes XYWH but `kwcoco_annotations_without_patch_and_sans_tiny_objects.json` has XYXY.

The other two annotation files do have the correct bbox format.
```
kwcoco_annotations_with_patch.json
kwcoco_annotations_without_patch.json
```

BTW, what's the filtering threshold for tiny objects? I think we should filter out tiny objects in the same way on the train/val splits, because the final evaluation wouldn't take those tiny objects into account.

**Comment by davidslater** [comment]
@yusong-tan

**Comment by yusong-tan** [comment]
@mzweilin Btw, the train/val splits from Armory should already be without tiny objects.
