### ISSUE TITLE
Poisoning: load everything before fitting model

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1520]
In the poison.py `load()` method, we call `self.fit()` before loading a couple other pieces. If some kind of error occurs when loading one these pieces, the user won't find out until after waiting for the model to train, which obviously can take a while.

I see no reason we can't have `self.fit()` be the last thing called inside `load()` (arguably it could go in a separate method since it's  not exactly a _load_ operation, but that's a separate point) to ensure that things fail faster

**Comment by davidslater** [comment]
We should make sure that there aren't any weird effects from loading downstream things (like attacks) prior to calling fit. Also, for interactive use, maybe we want to throw a warning if `fit = True` in the config but the user calls `run_benign` or `run_attack` prior to calling `fit()`.

**Comment by lcadalzo** [comment]
I'm noticing now that for evasion scenarios, we also `fit()` before loading the attack, test dataset, metric, and exporters. Assuming there are no weird effects from loading things before fitting, do you agree it makes sense to move fitting to the end of `load()`? My thinking, again, was that any loading errors would fail very slowly if the model has to fit first

**Comment by lcadalzo** [comment]
That's a good point, and difficult to test since the space of attacks one could use is limitless. Given that, I'd rather err on the side of what makes sense conceptually, which is to fit the model first. If an error occurs during these later loading steps, you'll of course want to ensure you don't lose your model progress, but that's a separate issue related to our discussion about how to structure Armory's `fit()` method
