### ISSUE TITLE
GPU Memory increase for CARLA video tracking scenario

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1543]
When running the undefended CARLA video tracking model, the memory fills up to 24GB on the third example, remains full on the fourth example, and then drops back off to ~16GB for the rest of the evaluation. This is for the undefended model, so this is causing OOM errors when performers add their defense. 

This behavior does not seem to be specific to the particular data examples, since when I set the dataset `"index"` in the config to skip the third and fourth examples, the same pattern as described earlier appears. 

To reproduce: 

```
python -m armory run scenario_configs/eval5/carla_video_tracking/carla_video_tracking_go
turn_advtextures_undefended.json --gpus 0
```

When debugging, it's helpful to set `max_iter` in the attack config to something smaller

**Comment by richardkxu** [comment]
Thanks for creating this issue! Just to add more details. These are the input video size and the GPU memory consumption for the first 5 videos:
```
(1, 33, 960, 1280, 3) | 15.64 GB
(1, 23, 960, 1280, 3) | 16.57 GB
(1, 35, 960, 1280, 3) | 23.02 GB
(1, 28, 960, 1280, 3) | 24.01 GB
(1, 37, 960, 1280, 3) | 17.76 GB
```
The GPU consumption start with 16~17GB and keep building up until it hits the max capacity (24 GB for 3090) and then drops to 17 GB and starts building up again.

**Comment by lcadalzo** [comment]
@richardkxu after if hits max capacity and then drops to ~17GB, I see it momentarily go back to max capacity at example 6/20 before dropping down to ~19GB and remaining there for the rest of the evaluation. Is that consistent with what you're seeing?

**Comment by lcadalzo** [comment]
clipping the number of frames does appear to significantly impact the GPU memory build-up. For each of the following (X, Y) pairs, X=max_frames and Y=maximum GPU memory observed (in GB) throughout the experiment over all 20 examples:

```
(5, 5)
(15, 10)
(25, 13
(30, 15)
(33, 16)
(34, 24)
(35, 24)
```

there's a threhsold effect at >= 34 frames, and I wonder if the spike happens at the third example since it's the first example for which num_frames >= 34. I mentioned that the same pattern of spiking on the third example occurred even when I skipped the third and fourth examples But the fifth example has 37 frames, so that's consistent with this hypothesis

**Comment by lcadalzo** [comment]
Closing due to the above merge, which will go into Armory 0.15.2
