### ISSUE TITLE
Python3.8 Windows Bug: Install pypiwin32 package to enable npipe:// support

### ISSUE THREAD

**Issue by seanpmorgan** [twosixlabs/armory#156]
Running armory with python3.8 on windows will throw this error:
`docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support`

This is a bit cryptic since pypiwin32 is already installed as a dependency in docker library. Since 3.8 there is a new way packages run post_install and this causes an underlying issue when importing pypiwin32.

It can be fixed by running:
`python <path-to-python-env>\Scripts\pywin32_postinstall.py -install`

Reference:
https://github.com/docker/docker-py/issues/1870
https://github.com/mhammond/pywin32/issues/1431

Alternatively it could be fixed by conda installing pywin32, but we do not currently package armory in conda.

**Comment by seanpmorgan** [comment]
Closing as there isn't a lot we can do for this and the fix is reported above. Perhaps we should start a FAQ list though.

**Comment by CTimmerman** [comment]
Afaik that's due to pywin32 not running the post install script with admin rights via the app store. Python 3.7 from python.org does.
