### ISSUE TITLE
Integrate Sleeper Agent attack for eval 6

### ISSUE THREAD

**Issue by swsuggs** [twosixlabs/armory#1583]
ART 1.11.0 includes the Sleeper Agent attack, which inherits from Witches' Brew.  One significant difference is that the attack adds a patch or trigger to test-time images, while Witches' Brew does not.  This may require a new scenario that inherits from Witches' Brew, or perhaps a more general one that both inherit from.

**Comment by davidslater** [comment]
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/poisoning_attack_sleeper_agent_pytorch.ipynb

**Comment by swsuggs** [comment]
Accomplished by #1609
