### ISSUE TITLE
Integrate Speech Commands Scenario

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1598]
https://github.com/Trusted-AI/adversarial-robustness-toolbox/commit/3f29055c800a020d4b5c18472a36a415c6238063

Backdoor attack: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/poisoning_attack_backdoor_audio.ipynb

**Comment by swsuggs** [comment]
Closed by #1615
