### ISSUE TITLE
New audio poisoning scenario?

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1601]
https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/poisoning_attack_backdoor_audio.ipynb

**Comment by swsuggs** [comment]
Is this intended to be different from #1598?

Also I had previously opened #1582 for audio poisoning.  Feel free to close one or the other

**Comment by davidslater** [comment]
I opened this for a full integration of the audio scenario. I think #1582 is just the integration of the attack.
