### ISSUE TITLE
advance armory operating system base to ubuntu nvidia 20.04

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1638]
Cribbed from Slack 30-sep-2022:

> I have a working docker image for this on noether with art 1.12, torch 1.12, tensorflow 2.10, tfds 4.6, cudatoolkit 11.6, and working off of ubuntu 20.04 nvidia base

This issue might want to wait until we have more CI tests to validate it. We want to advance the version for "in principle cleanliness" reasons rather than because we expect any immediate benefit.

**Comment by davidslater** [comment]
Base dockerfile on develop is already using ubuntu 20.04: https://github.com/twosixlabs/armory/blob/develop/docker/Dockerfile-base#L11

**Comment by christopherwoodall** [comment]
Issue closed by multiple merged PRs; see [`develop@docker/Dockerfile-*`](https://github.com/twosixlabs/armory/tree/develop/docker).
