### ISSUE TITLE
update CI release.yml to allow 0.16.0 release

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1641]
We need to catch the PyPI and dockerhub builds in `workflows/release.yml` to conform to the changes made in 0.16 develop.

It would be nice to have:
  1. workflow_dispatch on the job so that we don't need the arcane `curl` to kick off a job
  2. [push to test.pypi.org ](https://packaging.python.org/en/latest/guides/using-testpypi/)so that we can dry-run the release
 
The dry-run is helpful because PyPI burns version numbers on bad pushes. Docker doesn't allow dry-runs but does allow a push to replace a prior upload so the cost of errors is smaller.

**Comment by christopherwoodall** [comment]
Issue closed by [MERGED PR #1653](https://github.com/twosixlabs/armory/pull/1653) - [ORIG PR #1641](https://github.com/twosixlabs/armory/pull/1647)

**Comment by christopherwoodall** [comment]
Issue closed by [MERGED PR #1653](https://github.com/twosixlabs/armory/pull/1653) - [ORIG PR #1641](https://github.com/twosixlabs/armory/pull/1647)
