### ISSUE TITLE
Add global/local configs through armory configure

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#165]

**Comment by seanpmorgan** [comment]
More info: As the global config gets built out it would be a good idea to have a user friendly interface for updating and initial creation of the armory config file.

**Comment by seanpmorgan** [comment]
We've had a user issue where on their system they are prevented from writing to their home directory from within in a docker container. We'll need to expand this configuration script so that `armory_dir` can exist in a specified directory instead of auto-placed in user's home.

cc @Mohannadcse

**Comment by davidslater** [comment]
Main things that we want to configure:
PATHS
* armory_dir
* data_dir
* output directory - if we want that to be different

Look in `paths` 

Checks: if configure has been run, do you want to update?

**Comment by davidslater** [comment]
Will need to store `.armory` config in home dir to ensure proper access.
