### ISSUE TITLE
Re-organization of Scenario Configs

### ISSUE THREAD

**Issue by christopherwoodall** [twosixlabs/armory#1664]
Currently, scenario configs are stored by eval period in the `scenario_config` directory. I would like to propose sorting past scenarios into tactic directories and using a naming scheme for techniques, media(audio, image, video, text), and models labels. 

The directory structure would be modeled after [MITRE | ATLAS](https://atlas.mitre.org/); also see [AdvML Threat Matrix](https://github.com/mitre/advmlthreatmatrix/). Example root directory structure below:

```
┌─ ...
│
├─ scenarios/
│   │
│   ├─ 10-reconnaissance/
│   │
│   ├─ 20-resource-development/
│   │
│   ├─ 30-initial-access/
│   │
│   ├─ 40-model-access/
│   │
│   ├─ 50-execution/
│   │
│   ├─ 60-persistence/
│   │
│   ├─ 70-evasion/
│   │
│   ├─ 80-discovery/
│   │
│   ├─ 90-collection/
│   │
│   ├─ 100-attack-staging/
│   │
│   ├─ 110-exfiltration/
│   │
│   ├─ 120-impact/
│   │
│   ├─ 500-defenses/
│   │
│   └─ 1000-evaluations/
│
└── ...

```

**Comment by davidslater** [comment]
ATLAS is a useful way of thinking about adversarial AI from a defender's perspective. I don't think it will be helpful to set up our scenarios that way, however, as they are typically span multiple areas (Impact and Defense Evasion and ML Attack Staging for evasion; additionally Resource Development and Persistence for poisoning) and all of them have almost identical characterizations w.r.t. ATLAS.

The current `eval` breakdown is useful for the duration of the GARD program. Beyond that, however, I think that the cleanest breakdown is into evasion or poisoning and then by task.

**Comment by mwartell** [comment]
Per David's comment, this feature request is retracted as not particularly helpful to armory.
