### ISSUE TITLE
find a way to avoid a duplicate armory installation in Dockerfile-carla-mot

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1671]
As [noted in review](https://github.com/twosixlabs/armory/pull/1663#discussion_r992507113), there is a necessary but time consuming pair of RUNs at line 16-33.

If you have a local twosixarmory/pytorch base locally which is up-to-date, those RUNs are not needed. Because CI is stateless, it gets the base from dockerhub.com which would be the last published version.

**Comment by christopherwoodall** [comment]
[Fixed in PULL #1685](https://github.com/twosixlabs/armory/pull/1685)
