### ISSUE TITLE
breaking change to deepspeech in v0.16.0

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1677]
In v0.16.0 we had moved all dependency declarations into pyproject.toml. This works fine for `pip install`. However, PyPI.org does not accept the declaration for [romesco/hydra-lightning](https://github.com/romesco/hydra-lightning).

The romesco dependency is installed with

    pip install git+https://github.com/romesco/hydra-lightning/#subdirectory=hydra-configs-pytorch-lightning

But when publishing the wheel to PyPI that "direct reference" is not acceptable.  To fix that we created #1676 which moves that dependency to the armory deepspeech container and removes it from pyproject. 

This may be a problem for no-docker users.

**Comment by davidslater** [comment]
Just add a note in the docs for no-docker users here:
https://github.com/twosixlabs/armory/blob/master/docs/no_docker_mode.md
