### ISSUE TITLE
promote all scenarios check to CI task

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1700]
- [x] Create a Github Action to do the smoke test in `utils/run_scenario_configs.sh`.
- [x] Be selective about when we run it
- ~Optional: use the baseline output comparison mechanism from #1610~

**Comment by davidslater** [comment]
Is this done now, or are there additional things here? I don't see the boxes checked ^^

**Comment by christopherwoodall** [comment]
Awaiting a change from the [`rc0.16.1` branch](https://github.com/twosixlabs/armory/pull/1726/files).

The optional task is being left out for now. While we are collecting some run artifacts, the way in which armory mounts paths and stores outputs makes it challenging to extract them. Once this is fixed, we can begin analysis of the results to better implement comparisons.

**Comment by davidslater** [comment]
[tests/end_to_end/test_e2e_scenarios.py](https://github.com/twosixlabs/armory/blob/master/tests/end_to_end/test_e2e_scenarios.py#L29) will need to be updated to handle compute requirements better, but that can be done later - maybe with its own issue?

**Comment by christopherwoodall** [comment]
That can be edited in branch and is expected to grow.
