### ISSUE TITLE
discard yamllint from armory

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1707]
In the commit hooks and CI jobs there is a yamllint invocation. I believe that was placed there to guard against silly mistakes in Github Actions, but I think we're past that being an issue with editor support and fewer working on infrastructure.  The same goes for `environment.yml` and `mkdocs.yml` which are the only other yaml files in the repo. Moreover the current `yamllint` rejects some utterly valid syntax (e.g. multiline blocks) which requires silly rewriting and lint overrides.

Also, `yamllint` will not help us when we turn config.json into experiment.yaml, because syntactic validity is the smaller part of having a valid experiment. Better will be to use (for example) hyrda-zen to validate the experiment contents which indirectly validates the yaml syntax.  See also #1618.

**Comment by davidslater** [comment]
I am fine with this. However, for experiment.yaml, I would like to enforce some basic linting (even if we don't do yamllint), to keep spacing consistent and lexical ordering of keys, if nothing else.

We can add that in once we move to yaml in experiments, though.
