### ISSUE TITLE
CARLA Video Tracking exporting boxes to multiple locations

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1712]
There are two `ExportMeters` set up for the CARLA video tracking scenario: one that outputs images with boxes and one that doesn't. The latter `ExporMeter` is outputting to, e.g., `/armory/outputs/2022-10-25T183719.308044/` whereas the former is (correctly) outputting to `/armory/outputs/2022-10-25T183719.308044/saved_samples`. Both sets of boxes should be outputted to the same subdirectory

**Comment by lcadalzo** [comment]
correct. this is what prompted me creating the issue, is that I was working with carla-mot

**Comment by davidslater** [comment]
The most straightforward solution, I think, is to not call `super().load_export_meters()` and just replicate any needed functionality in the `load_export_meters` overridden function.

**Comment by davidslater** [comment]
Oh, I see, we want both.

**Comment by davidslater** [comment]
Is this as simple as changing this:
https://github.com/twosixlabs/armory/blob/develop/armory/scenarios/carla_video_tracking.py#L78
to
```            self.export_dir,```
