### ISSUE TITLE
Restrict pre-commit hook to staged diffs only

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1717]
Currently, all of the linting tools (black, flake, json_format, yamllint) run across all files in the repo, whether or not they are in source control and whether or not they have staged changes.

This feature would limit changes to files that are A) in source control and B) have staged changes.

We should be able to use something like `git diff HEAD --name-only` to provide a list of potential items for linting and then provide them as input into the various tools.

**Comment by christopherwoodall** [comment]
I'll add this to #1708

**Comment by davidslater** [comment]
Sounds good. Note that this will make the pre-commit hook differ from CI. CI should still test all of the files in the repo, but has the benefit that all files it has access to will be in source control and that we don't care too much about a few second delay there (but it can be annoying when iterating against yamllint or flake in local dev).

**Comment by christopherwoodall** [comment]
Added an `ARMORY_CI_TEST` flag to [determine what files to scan](https://github.com/twosixlabs/armory/blob/9b5e1646f09578bc36e87f24693f8c83fc2f17e0/tools/pre-commit.sh#L10). By default(running locally) it will run `git diff | grep`, if the `ARMORY_CI_TEST` flag is set it will run `git lstree | grep`.
