### ISSUE TITLE
check tide dependency for tide metrics

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1764]
In #1762 `armory run` works if `tidecv` is in pyproject `dependencies` but fails if moved to `engine`. Find out what's wrong and fix it once #1762 is merged.

**Comment by davidslater** [comment]
`engine` isn't installed by default in the docker images. It only installs `dependencies` by default.

If you do a `pip install ".[pytorch]"` it should work.
Alternatively, we would need to update the pip installs in the `Dockerfile-base` image.

A pip dependency added to `engine` doesn't hit the CI testing, except in https://github.com/twosixlabs/armory/blob/master/.github/workflows/2-test-stand-alone.yml
It won't make any difference in
https://github.com/twosixlabs/armory/blob/master/.github/workflows/3-test-docker.yml

**Comment by christopherwoodall** [comment]
In `rc0.16.1` the proper dependencies have been added to the Dockerfiles. See [link](https://github.com/twosixlabs/armory/blob/rc0.16.1/docker/Dockerfile-pytorch#L14)
