### ISSUE TITLE
[BUG]: Poisoning activation defence gives error while extracting outputs of activation layers

### ISSUE THREAD

**Issue by Uncertain-Quark** [twosixlabs/armory#1765]
### Description of the bug

This could be because the Resnet50 version of tensorflow from https://github.com/keras-team/keras/blob/b80dd12da9c0bc3f569eca3455e77762cf2ee8ef/keras/applications/resnet.py#L76 is not declared as tf.keras.models.sequential whereas the get_activations in https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/estimators/classification/tensorflow.py requires the model to be tf.keras.models.Sequential.

`ValueError: Method get_activations is not supported for non-Sequential models.`

Is there any quick fix?

### Steps To Reproduce

```
cd scenario_configs/eval6/poisoning/audio_dlbd/baseline_defenses
armory run audio_p10_activation_defense.json --no-docker --use-gpu
```

**Comment by davidslater** [comment]
@swsuggs have you run into this error?

**Comment by davidslater** [comment]
@Uncertain-Quark Can you list the armory log output here? I was not able to reproduce.

**Comment by davidslater** [comment]
Nvm, can reproduce. I think I have a fix.

**Comment by davidslater** [comment]
The above PR should fix it. If you want to test locally, the change is only a single line. (Wrapping the functional model with a sequential one.)
