### ISSUE TITLE
Datasets gets saved to wrong place in container (does not survive docker container)

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#177]
Datasets get downloaded to `/home/<host user>/.armory/datasets` on the docker container, which is not shared with the host. Probably an issue with `armory.path` or the docker container invocation.

**Comment by seanpmorgan** [comment]
https://github.com/twosixlabs/armory/pull/162 should fix I believe

**Comment by davidslater** [comment]
It does.
