### ISSUE TITLE
[BUG]: Unspecified dependency of "yolox" for Eval6 MOT scenario

### ISSUE THREAD

**Issue by ShengYun-Peng** [twosixlabs/armory#1782]
### Description of the bug

1. `Yolox` ([ByteTrack repo](https://github.com/ifzhang/ByteTrack)) is installed in "carla-mot" docker: https://github.com/twosixlabs/armory/blob/1d6caa9166313c1409edbbc5f089d2bc774b5230/docker/Dockerfile-carla-mot#L5-L9
2. But it is not installed as per the MOT json file: https://github.com/twosixlabs/armory/blob/c2d2a0c894acca5e5bbff7ebbff56fe7f9a536b2/scenario_configs/eval6/carla_mot/carla_mot_adversarialpatch_undefended.json#L74-L76
3. So I will get an error when importing yolox: https://github.com/twosixlabs/armory/blob/c2d2a0c894acca5e5bbff7ebbff56fe7f9a536b2/armory/baseline_models/pytorch/carla_mot_frcnn_byte.py#L15-L17

### Steps To Reproduce

`armory run scenario_configs/eval6/carla_mot/carla_mot_adversarialpatch_undefended.json --no-docker`

**Comment by davidslater** [comment]
I think we ran into issues with adding this as a pyproject set of separate requirements, due to weirdness with Cython and cython-bbox ordering. @christopherwoodall do you recall?

To fix, you will want to copy the dockerfile in your local environment and run:
```
pip install --no-cache-dir \
    git+https://github.com/ifzhang/ByteTrack.git \
    thop \
    lap \
    Cython

pip install --no-cache-dir \
    cython-bbox
```

**Comment by dxoigmn** [comment]
The issue we saw was that that repo wants torch installed when running setup.py, which prohibited us from also putting it in our pyproject.toml. The solution you provided is a fine work around other than forking their repo and fixing the setup.py issue.

**Comment by christopherwoodall** [comment]
There was an issue with the initial build of the MOT containers, a fixed version was pushed by @davidslater shortly after. Please check to ensure the current image has an Image ID of `73d059449f2d`.

```
$ docker image ls | grep twosixarmory/carla-mot
twosixarmory/carla-mot           0.16.1                                73d059449f2d   16 hours ago   14.3GB
twosixarmory/carla-mot           latest                                73d059449f2d   16 hours ago   14.3GB
```

If the Image ID does not match, run `docker pull twosixarmory/carla-mot:0.16.1` and then confirm the Image ID is correct.

**Comment by christopherwoodall** [comment]
The issue lies in a [remote dependency](https://github.com/ifzhang/ByteTrack).
