### ISSUE TITLE
Code modifications in "pytorch_object_detector.py" (art)

### ISSUE THREAD

**Issue by ShengYun-Peng** [twosixlabs/armory#1785]
Please check the details [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/issues/1943).

**Comment by swsuggs** [comment]
For eval6 purposes, you should be able to create your own model that inherits the carla MOT [PytorchTracker](https://github.com/twosixlabs/armory/blob/c2d2a0c894acca5e5bbff7ebbff56fe7f9a536b2/armory/baseline_models/pytorch/carla_mot_frcnn_byte.py#L30), and overrides the ART function in question.  Then, modify the ```model``` section of the config (```module``` and ```name```) to point to your code.

**Comment by ShengYun-Peng** [comment]
> 

Thanks, @swsuggs. Our defense is a preprocessor, so we try to minimize the code modification into mot model itself. The chunk of code we attempt to change is in `_get_loss`, which starts with an underscore (not supposed to be overridden?).

**Comment by swsuggs** [comment]
Makes sense.  We can see what Beat says on the art issue.
