### ISSUE TITLE
TFDSv4: Handle non-standard dataset paths

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1802]
We assume that datasets are stored in `<dataset_dir>/<name>/<version>/`. However, some have additional directories that may be related to builder configs (e.g., ucf101) or community datasets.

**Comment by lcadalzo** [comment]
See [this](https://github.com/twosixlabs/armory/pull/1800#issuecomment-1337515761) comment, which prompted the issue

**Comment by lcadalzo** [comment]
Closing due to #1842
