### ISSUE TITLE
Integrate DP-Instahide

### ISSUE THREAD

**Issue by swsuggs** [twosixlabs/armory#1822]
Defense to be included in upcoming ART release

**Comment by lcadalzo** [comment]
From 12/20 meeting: 
1. See https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/poisoning_defense_dp_instahide.ipynb

2. From Farhan: "it’s a trainer similar to the AdversarialTrainerMadryPGD which has been used in previous evals. The only issue is that an object needs to be instantiated and passed as a parameter to the trainer"

**Comment by lcadalzo** [comment]
@swsuggs @jprokos26 was #1841 supposed to be included in 0.16.2 release that occurred last week? Assuming this is needed for Eval 6 I would think so, but not sure if I'm missing context
