### ISSUE TITLE
Frozen bboxes in eval6 mot scenario after upgrading to 0.16.2

### ISSUE THREAD

**Issue by ShengYun-Peng** [twosixlabs/armory#1856]
Though “export batches” is working in 0.16.2, the plotted bboxes don’t seem to be updated along with the frame id. Frame 0 and 7 have the same bboxes below.

<img width="1020" alt="Screen Shot 2023-01-10 at 3 10 42 PM" src="https://user-images.githubusercontent.com/84164548/211659738-e6e2ea2e-cfa0-46b4-9203-65b71bf82476.png">
<img width="1018" alt="Screen Shot 2023-01-10 at 3 11 03 PM" src="https://user-images.githubusercontent.com/84164548/211659789-08f4ec2f-4ad2-40a6-8e2e-90eb29f8b47f.png">

**Comment by ShengYun-Peng** [comment]
Found the culprit: Replace `frame_id ` with `n_frame` https://github.com/twosixlabs/armory/blob/066db8467a425403b980c5d408e0d6dbdca5c7d1/armory/instrument/export.py#L437

Also, `frame_id` seems redundant now:
https://github.com/twosixlabs/armory/blob/066db8467a425403b980c5d408e0d6dbdca5c7d1/armory/instrument/export.py#L433

**Comment by lcadalzo** [comment]
thanks @ShengYun-Peng for reporting this. I've added the PR mentioned above to fix this, and this change should go into an impending 0.16.3 patch release
