### ISSUE TITLE
[BUG]: Depth images are saved incorrectly

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#1858]
### Description of the bug

It is possible for depth images to have non-integer values when passed to:
https://github.com/twosixlabs/armory/blob/066db8467a425403b980c5d408e0d6dbdca5c7d1/armory/instrument/export.py#L68
For example, the value of the depth image pixel (in RGB) could be `[55.255993 61.999996  9.999999]`. In the ideal case these would be rounded to the nearest integer, however, `get_sample` always rounds down:
https://github.com/twosixlabs/armory/blob/066db8467a425403b980c5d408e0d6dbdca5c7d1/armory/instrument/export.py#L100
As a result of rounding down, this causes noise in the saved depth images on disk and can cause large perturbations as a result.

### Steps To Reproduce

1. Examine `255*x_i_mode` just before this line:
https://github.com/twosixlabs/armory/blob/066db8467a425403b980c5d408e0d6dbdca5c7d1/armory/instrument/export.py#L100
3. In the case of depth images, the pixel values around the patch will be non-integer (after multiplying by 255).

**Comment by lcadalzo** [comment]
impending 0.16.3 patch release will contain this fix
