### ISSUE TITLE
Missing modules error in the new Armory 0.4

### ISSUE THREAD

**Issue by Mohannadcse** [twosixlabs/armory#186]
I've downloaded Armory using the `pip install armory-testbed`. 
But I received the following error **ModuleNotFoundError: No module named 'art'** after running the command `armory download-all-data`

![image](https://user-images.githubusercontent.com/15859139/74970420-f0272400-53e3-11ea-9928-5107db1d30f5.png)

**Comment by Mohannadcse** [comment]
Update, 
I installed **ART** using `pip install adversarial-robustness-toolbox`, then installed `pip install boto3`. Now I'm stuck with this error **requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/images/twosixarmory/tf1:0.4.0/json**

Even I receive the following error after rinning `armory clean`
**docker.errors.NotFound: 404 Client Error: Not Found ("manifest for twosixarmory/tf1:0.4.0 not found: manifest unknown: manifest unknown")**

**Comment by davidslater** [comment]
Hi Mohannad - we're working on this now and we'll have a fix out soon.

**Comment by seanpmorgan** [comment]
Hi Monnad were working on some release issues and should have a new version
available by tomorrow. At latest. Apologies for the notification well email
you directly when it's fixed. This should be the last time we have build
breaks like this

**Comment by seanpmorgan** [comment]
Hi @Mohannadcse please try the 0.4.1 version when you get a chance. Let us know if there are issues and we can re-open this if needed.

**Comment by Mohannadcse** [comment]
Thanks Sean. 
I got the new Armory version. However, now I receive a different error after running any example. This is the error **ValueError: A `module` must be specified in dataset json**

**Comment by seanpmorgan** [comment]
> Thanks Sean.
> I got the new Armory version. However, now I receive a different error after running any example. This is the error **ValueError: A `module` must be specified in dataset json**

Apologies, we'll be updating the [armory-examples](https://github.com/twosixlabs/armory-example) repository tomorrow. If however you would like to test tonight run one of the examples in the central repo:
https://github.com/twosixlabs/armory/tree/master/examples

As seen in the release notes the dataset schema has changed.

**Comment by Mohannadcse** [comment]
Thanks for the update. I'm using now the new example. However, still the permission issue exists **PermissionError: [Errno 13] Permission denied: '/armory/tmp/eval-config.json'**
