### ISSUE TITLE
Bug: issue with exported video tracking samples box location

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1861]
When running `scenario_configs/eval6/carla_mot/carla_mot_adversarialpatch_undefended.json` with `export_batches` set to `true`, I've noticed that the ground-truth and predicted boxes from the first frame are being overlaid onto _all_ frames exported, rather than just the first

**Comment by swsuggs** [comment]
Is this related to [1856](https://github.com/twosixlabs/armory/issues/1856)?

**Comment by lcadalzo** [comment]
duplicative in fact, thanks for pointing this out. I'll close this one
