### ISSUE TITLE
How to properly cite armory?

### ISSUE THREAD

**Issue by groppcw** [twosixlabs/armory#1865]
Hi! Armory has come up a few times as I review literature for my dissertation, and I'd like to properly reference it when I discuss it. Papers I've found that utilize it seem to cite it inconsistently, such as citing other papers that discuss it rather than the project itself, or leaving a link to some part of the github rather than a full citation. Since these references are inconsistent, I've also had a harder time tracking down research papers that utilize it. Some of the similar toolkits I've looked at (such as https://github.com/QData/TextAttack) have preferred citation information in their readme, but I didn't see anything here and didn't find anything obvious in my searches online either. Is there a preferred method for this?

My first thoughts were to either cite this github directly (although I've seen different papers cite different pages of it, which makes search more difficult), or this webpage (https://www.darpa.mil/news-events/2021-12-21) that describes the project a bit. I wanted to ask if there was a preference, and to suggest that the answer be added to the readme such that a convention becomes established for future publications. There's some impressive work being done with this, and I'd like to ensure you all get the credit you deserve!

Thanks.

**Comment by Embeddave** [comment]
You all might want to add Zenodo integration to have a citable DOI for each release:
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

Additionally you can add a citation.cff to make it easier to figure out how to cite.
https://citation-file-format.github.io/
The GitHub integration with that file format will give you a button on the right hand side of your repo's page that will give anyone who clicks it something they can just copy-paste.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by mwartell** [comment]
Thanks @groppcw for pointing out this need and to @Embeddave for information on how to achieve this.

I have registered Armory with Zenodo and will add the DOI and citation tag upon the next release when I'll also add the `citation.cff`.  Since our next release might not happen for ~6 months, I may make a "citability" release shortly to bootstrap the indexing system.

**Comment by Embeddave** [comment]
👍 

@mwartell If it helps you can upload previous releases directly through the Zenodo web UI to make sure those get a DOI. 



Is it possible to archive a GitHub repository, before it was enabled on Zenodo?

https://help.zenodo.org/

> If you want to archive some of your old releases, you can always download a release ZIP from GitHub and upload it to Zenodo using our web interface as a regular upload.

Not quite as nice as the automagic integration but gets the job done.

**Comment by mwartell** [comment]
DOI [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7561756.svg)](https://doi.org/10.5281/zenodo.7561756)
has been registered for Armory v0.16.4
