### ISSUE TITLE
clear Dynamo to accept new submissions for eval7 and release eval7 armory-uploader wheel

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1951]
The sabot db need to be cleared before the eval7 submission period. 

We need a new armory-uploader wheel with hardcoded `eval7` in it.

**Comment by swsuggs** [comment]
Also add UCIU or whatever we are calling Bo Li's group from Illinois

**Comment by swsuggs** [comment]
Eval 7 is completed.
