### ISSUE TITLE
infra activities for eval 7 kickoff

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1961]
- [x] update docx invitation
- [x] release new armory-upload with `eval7` s3 destination folder
- [x] update AWS IAM perms to allow write-only to `eval7` folder
- [x] reconcile (adopt in toto?) Donizetti's master email list
- [x] backup and clear DynamoDB
- [ ] create Armory v0.18.0 AMI for evalboxes
- [x] figure out better model-weights mechanism
- [ ] implement  #1962

**Comment by mwartell** [comment]
Armory-upload currently routes submitted model weights into an evalX folder (with everything else).  But armory only knows to [look](https://github.com/twosixlabs/armory/blob/3efd21652cfdc8cd192681e9daf58a4b08e82db4/armory/data/utils.py#L66) for them under model-weights .  I think in eval6 I sometimes copied the weights into model-weights  so armory could find them easily.  Going forward, what do you prefer: updating armory to search deeper (might be tricky to tell it which eval folder to look in), just having people download the weights themselves, or something else?

**Comment by swsuggs** [comment]
Hey that was my question . . .

But what if we just have armory-upload put them in both spots, then we can delete model-weights when no longer needed?

**Comment by swsuggs** [comment]
Eval 7 is completed.
