### ISSUE TITLE
Add / rework dataset tests for large datasets

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#238]
Larger datasets (UCF, LibriSpeech, for instance) require a lot of processing to test. UCF101 takes ~2 hours to extract for TFDS. They also require a number of dependencies which complicate testing outside of the Docker containers.

**Comment by seanpmorgan** [comment]
Hmmm ~2hours including the download or just extracting the necessary data? Is this only a cost for the first time its ran?

**Comment by davidslater** [comment]
The extraction is what takes a long time - formatting it for TFDS. It's only a cost for the first time.

**Comment by davidslater** [comment]
Fixed by data caching.
