### ISSUE TITLE
Ensure download_all_data works for new generators

### ISSUE THREAD

**Issue by seanpmorgan** [twosixlabs/armory#239]
Given the new function calls, we'll want to make sure we have a working way for users to download all datasets to disk.

**Comment by seanpmorgan** [comment]
A better approach may be to have datasets downloaded per scenario.

**Comment by davidslater** [comment]
yes, something like `armory download_all_data <scenario>`, or `armory download_all_data <eval_1_scenarios>`, where the latter could have a config file of the names of datasets (and baseline models). It could run download/extract them, test them, etc., but be limited to a particular list of datasets.
