### ISSUE TITLE
Resize images using tf.data pipeline

### ISSUE THREAD

**Issue by seanpmorgan** [twosixlabs/armory#255]
Currently we ensure image shape through the pre-processing function specified in each baseline model file. This is slow since we're not utilizing the tf.data pipeline which will pre-fetch and run this optimally. Instead, it should be a configuration that is passed to the dataset call and ran as a map function.

Example:
https://github.com/twosixlabs/armory/blob/master/armory/baseline_models/keras/keras_inception_resnet_v2.py#L14

**Comment by seanpmorgan** [comment]
This will also allow us to remove the NotImplemented batch_size > 1 for imagnette and ucf101:

https://github.com/twosixlabs/armory/blob/master/armory/data/datasets.py#L568
https://github.com/twosixlabs/armory/blob/master/armory/data/datasets.py#L377

**Comment by davidslater** [comment]
We should also think about resampling operations for audio.

**Comment by davidslater** [comment]
We would like to move the preprocessing functions inside of the model boundaries, and likely remove the standard preprocessing component from the dataset pipeline.
