### ISSUE TITLE
Update tests to use `armory exec`

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#264]
Use `exec` command in armory in the` __main__` entrypoint, to run pytest inside the specified container with the given set of pytest args. This will prevent some of the more complicated volume mounting problems.

**Comment by davidslater** [comment]
This may require exit code passthrough from the exec_run command in 
https://github.com/twosixlabs/armory/blob/master/armory/docker/management.py#L65-L71

(Currently, we just take the output and print.)
https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.exec_run
It's unclear how to both stream the results and return the exit code.

**Comment by seanpmorgan** [comment]
Yeah so the stream output isn't parsed for errors in the GitHub action:
https://github.com/twosixlabs/armory/pull/286/checks?check_run_id=519555964

We could work towards returning exit code and results, but I'm unsure of the benefit of that. Currently the tests don't mount any volumes anyway so unclear of the benefits for using exec here.

**Comment by davidslater** [comment]
Let's close for now.
