### ISSUE TITLE
Move all datasets to TFDS model

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#284]
This would simplify/unify a lot of our code and dataset processing.

We would need to update the following datasets:
- [x] digit (currently numpy)
- [x] imagenet_adversarial (currently custom TFRecordDataset)
- [x] german_traffic_sign (currently numpy)

**Comment by davidslater** [comment]
Then datasets methods could then simply look like:
```python
def mnist(*args, **kwargs):
    """                                                                                  
    Handwritten digits dataset:                                                          
        http://yann.lecun.com/exdb/mnist/                                                
    """ 
    return _generator_from_tfds("mnist:3.0.0", *args, **kwargs)
```

**Comment by seanpmorgan** [comment]
Agree this is a nice standardization. If we need to create PyTorch generators for performance reasons, this work will not be of value to that but it still cleans up our TF generators so I would certainly be in favor of this
