### ISSUE TITLE
Support CUDA 9.x limited devices

### ISSUE THREAD

**Issue by seanpmorgan** [twosixlabs/armory#292]
We've been asked to support GPU devices without capability to run CUDA10.1. This should be feasible for the pytorch docker container since the binary can support multiple CUDA versions. Likely little performance regression by doing this. Turing cards will be unsupported but we can work through that if the need arises:
https://github.com/twosixlabs/armory/blob/master/docker/pytorch/Dockerfile#L10

**Comment by davidslater** [comment]
Will close this following merge of #536 (which documents this).

Recommend users manually rebuild pytorch docker container with CUDA 9. Note that TensorFlow versions require CUDA 10.

Making this standard for PyTorch would have removed support for Turing cards and removed many performance optimizations available in CUDA 10.
