### ISSUE TITLE
Custom model + pre-trained weights

### ISSUE THREAD

**Issue by arashno** [twosixlabs/armory#373]
Hello,
I have trained my custom PyTorch model on the MNIST dataset (outside armory). I have saved the weights in weights.pt file.
Now, I am trying to load the saved weights and then evaluate my trained model using FGSM attacks in armory.

This is my .json config file:

```
{
    "adhoc": {
        "batch_size": 64,
        "epochs": 0
    },
    "attack": {
        "budget": null,
        "knowledge": "white",
        "kwargs": {
            "eps": 0.2
        },
        "module": "art.attacks",
        "name": "FastGradientMethod"
    },
    "dataset": {
        "module": "armory.data.datasets",
        "name": "mnist"
    },
    "defense": null,
    "evaluation": {
        "eval_file": "evaluations.fgm_attack"
    },
    "metric": null,
    "model": {
        "model_kwargs": {},
        "module": "custom_models.mnist",
        "weights_file":"weights.pt",
        "name": "get_art_model",
        "wrapper_kwargs": {}
    },
    "sysconfig": {
        "docker_image": "twosixarmory/pytorch:0.4.1",
        "external_github_repo": null,
        "use_gpu": false
    }
}

```
This is my custom_models.mnist.py code:

```
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
from art.classifiers import PyTorchClassifier


def preprocessing_fn(img):
    # Model will trained with inputs normalized from 0 to 1
    img = img.astype(np.float32) / 255.0
    return img


class MNISTNet(nn.Module):
    """
    Sample CNN for MNIST
    """
    def __init__(self):
        super(MNISTNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.conv2 = nn.Conv2d(32, 64, 3, 1)
        self.dropout1 = nn.Dropout2d(0.25)
        self.dropout2 = nn.Dropout2d(0.5)
        self.fc1 = nn.Linear(9216, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = x.permute(0,3,1,2)
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = F.max_pool2d(x, 2)
        x = self.dropout1(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.dropout2(x)
        x = self.fc2(x)
        output = F.log_softmax(x, dim=1)
        return output


def make_mnist_model(**kwargs):
    return MNISTNet()

def get_art_model(model_kwargs, wrapper_kwargs):
    print("*************************************", wrapper_kwargs)
    model = make_mnist_model(**model_kwargs)
    wrapped_model = PyTorchClassifier(
        model,
        loss=nn.CrossEntropyLoss(),
        optimizer=torch.optim.Adam(model.parameters(), lr=0.003),
        input_shape=(1, 28, 28),
        nb_classes=10,
        clip_values=(0.0, 1.0),
        **wrapper_kwargs
    )
    return wrapped_model
```

Currently, armory does not load the weights and throw no error! I think it just uses randomly initialized weights and proceeds.

1- Where should I put the weights.pt file so that armory can load the pre-trained weights?

2- No matter what arguments (channel_index=1 or input_shape) I give to the PyTorchClassifier, the data passed to my model is always channel last (NWHC). I temporary solved this issue by using x = x.permute(0,3,1,2) in my model but what is a better solution?

Thanks

**Comment by seanpmorgan** [comment]
Hi @arashno! Just want to start by saying there is a lot of work going into the repo right now, so best to check the updated documentation once a 0.6 release is made next week.

Will answer your questions currently though:

1. Weight files should be loaded from the `saved_model_dir`. This defaults to `~/.armory/saved_models` unless you've modified it with `armory configure`.  More information regarding armory paths [can be found here](https://github.com/twosixlabs/armory/blob/master/docs/docker.md#docker-volume-mounts
). An example of loading weights for a baseline model on the [master branch can be seen here](https://github.com/twosixlabs/armory/blob/master/armory/baseline_models/pytorch/mnist.py#L53-L64). Note, that the download from s3 portion is only needed so we can provide weights to users. If you have your own weights this is not needed.

2. Right now we would probably recommend either permute in the model or adding a numpy transpose in the `preprocessing_fn` for that model. We'll be discussing the data loading in a FAQ section. The plan is to provide TF Tensor generators and PyTorch Tensor generators once ART supports attacks/defences for framework specific inputs. Then we can have the pytorch generator return the expected NCHW

**Comment by seanpmorgan** [comment]
Small change in pytorch weight loading that might be relevant:
https://github.com/twosixlabs/armory/pull/381
