### ISSUE TITLE
Issue selecting GPUS

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [twosixlabs/armory#437]
Hello,

As indicated by the documentation I added `"gpus": "1",` to the configuration file. However, all GPUs are used, and because one already has a job running on it the evaluation script fails because it gets an out of memory error. According to `tf` logs all 5 GPUs are used:

`Adding visible gpu devices: 0, 1, 2, 3, 4, 5`

How can I fix that?

**Comment by seanpmorgan** [comment]
Hi @GuillaumeLeclerc what version of armory are you using. We're currently in the final steps of testing 0.6.0-rc2 which will include this functionality. Expect a 0.6.0 stable release sometime today

**Comment by GuillaumeLeclerc** [comment]
armory 0.5.0 for the testbed and `da216ccf4c60d3afd3f056da7a37300bab817629` for the example repo

**Comment by seanpmorgan** [comment]
Hi @GuillaumeLeclerc we've tested and this issue is fixed on our 0.6.0 release candidates. Will be releasing the stable release later today. Closing but please feel free to re-open if it doesn't work on 0.6.0
