### ISSUE TITLE
Docker images are probably too large

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [twosixlabs/armory#456]
Some other containers including pytorch+CUDA are less than 4x smaller than the ones you provide.

Eg: https://hub.docker.com/r/anibali/pytorch/tags

**Comment by davidslater** [comment]
The size of our compressed current containers (uncompressed) are:
pytorch - 4.13 GB (8.05 GB)
tf1 - 3.76 GB (7.92 GB)
tf2 - 4.03 GB  (8.28 GB)

The pytorch:latest from anibali is 1.79 GB (4.06 GB)

Looking into differences.

**Comment by davidslater** [comment]
The easiest win is to remove conda `.tar.bz2` files using `conda clean --tarballs` or something similar. This frees up 1.12 GB on the pytorch image:
```
---------------------------------------------------
Total:                                      1.12 GB

Proceed ([y]/n)? y
```

Removing the pip cache (/root/.cache/pip) gets us 174 MB.


Other possible culprits:
```
-rw-r--r-- 1 root root 391622760 Oct 27 23:06 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
-rw-r--r-- 1 root root 109361616 Jul 12  2019 /usr/lib/x86_64-linux-gnu/libnccl.so.2.4.8
```
These are installed in ours but not in the other.

There's a major difference between the size of cuda folders:
```
24M	/usr/local/cuda/
vs 
680M	/usr/local/cuda/
```
This is due to anibali only compiling the target for `libcudart`, where our container has a lot of underlying libs:
```
68M	libcublas.so.10.0.130
99M	libcufft.so.10.0.145
58M	libcurand.so.10.0.130
133M	libcusolver.so.10.0.130
57M	libcusparse.so.10.0.130
11M	libnppial.so.10.0.130
3.8M	libnppicc.so.10.0.130
1.3M	libnppicom.so.10.0.130
6.9M	libnppidei.so.10.0.130
46M	libnppif.so.10.0.130
24M	libnppig.so.10.0.130
6.0M	libnppim.so.10.0.130
16M	libnppist.so.10.0.130
2.8M	libnppitc.so.10.0.130
8.1M	libnpps.so.10.0.130
85M	libnvgraph.so.10.0.130
1.1M	libnvjpeg.so.10.0.130
3.3M	libnvjpeg.so.10.0.318
4.5M	libnvrtc-builtins.so.10.0.130
20M	libnvrtc.so.10.0.130
```

There is another GB that we can't remove, which comes from the additional dependencies related to tensorflow_datasets (including tensorflow_core, pyarrow, _solid_k8, botocore).

Not sure if there are other things that we are missing.

@seanpmorgan Thoughts?

**Comment by davidslater** [comment]
The size of `/usr/lib` and `/usr/local` are from the `10.0-cudnn7-runtime-ubuntu18.04` base image, so I don't want to mess with those. I would prefer to have a larger image than to have to do a custom cuda install.

**Comment by davidslater** [comment]
Cleaning conda and pip have reduced image sizes by 15-20%. Of what remains, essentially everything is one of cuda (1.5 GB), pip packages (2.2 GB), or conda packages (2.9 GB).
```
$ docker images
REPOSITORY                  TAG                               IMAGE ID            CREATED             SIZE
twosixarmory/pytorch        0.7.0-dev                         4dfd5689772f        8 minutes ago       6.56GB
twosixarmory/pytorch-base   0.7.0-dev                         6521a3d8626a        8 minutes ago       6.55GB
twosixarmory/tf2            0.7.0-dev                         8b0e016ef609        11 minutes ago      7.04GB
twosixarmory/tf2-base       0.7.0-dev                         21f45caf6831        11 minutes ago      7.03GB
twosixarmory/tf1            0.7.0-dev                         72f061f41a21        13 minutes ago      6.74GB
twosixarmory/tf1-base       0.7.0-dev                         8f6212353a2c        14 minutes ago      6.73GB
twosixarmory/armory         0.7.0-dev                         ca386084ac10        16 minutes ago      3.12GB
twosixarmory/pytorch        0.6.0                             f0b76577ffb9        4 days ago          8.05GB
twosixarmory/tf1            0.6.0                             4d673d90e86e        4 days ago          7.92GB
twosixarmory/tf2            0.6.0                             79a142a290bc        4 days ago          8.28GB
nvidia/cuda                 10.0-cudnn7-runtime-ubuntu18.04   a9fac7264a6d        4 months ago        1.3GB
```
