### ISSUE TITLE
running armory without docker

### ISSUE THREAD

**Issue by jesus-villalba** [twosixlabs/armory#457]
Hi, some of use cannot install docker in our grids. Can you provide some instructions of how to manually configure our environment to be able to run armory without docker? e.g., list of python packages, environment variables, other dependencies, etc.
Thanks

**Comment by davidslater** [comment]
There are a couple of additional things that we'll need to do on our end - update how we're referencing paths, and adding some command line args to prevent evaluation launching trying to contact docker - but I think it's pretty doable in the short term.
