### ISSUE TITLE
Consider bumping to PyTorch 1.5

### ISSUE THREAD

**Issue by seanpmorgan** [twosixlabs/armory#479]
I think we want to avoid chasing each release of TF and PyTorch, but there is newly added support for "Channel Last" memory format in PyTorch 1.5:
https://pytorch.org/blog/pytorch-1-dot-5-released-with-new-and-updated-apis/#channels-last-memory-format-for-computer-vision-models-experimental

This could simplify our dataset generators because both frameworks would have support for the data format we currently load. There would no longer be a need to permute the shapes of data in models as is done here:
https://github.com/twosixlabs/armory/blob/master/armory/baseline_models/pytorch/cifar.py#L30

It is true that we are actively looking to build PyTorch data generators https://github.com/twosixlabs/armory/issues/455 that could handle the dimension swap, but since ART is slowly adding support for torch Tensors, it's likely we'll need NumPy support for some attacks/defenses into the foreseeable future.

**Comment by davidslater** [comment]
That update would definitely be nice. Do you know what the ramifications of the "experimental" tag are?

**Comment by davidslater** [comment]
We could also consider bumping up to TF 2.2 at the same time. Perhaps after the first evaluation set of submissions, when we bump up to ART 1.3?
