### ISSUE TITLE
GPU Memory Leak in UCF101 Scenario with PyTorch

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#502]
With PyTorch, there is a memory leak in the UCF101 scenario on the following line: https://github.com/twosixlabs/armory/blob/712c2ae83a4ef94f1c75ff166c80652cd4c8512c/armory/scenarios/video_ucf101_scenario.py#L103

Since no `batch_size` is specified for the `predict` call, it defaults to 128 in ART's `PyTorchClassifier`. This  causes PyTorch to allocate memory for each unique batch size since most batch sizes are less than 128. Adding `batch_size = 1` forces constant memory.

**Comment by davidslater** [comment]
So, if I understand this correctly, if the passed in batch size is less than 128, it doesn't use the already allocated batch size 128 (implicitly using masking for the missing parts of the batch), it instead creates a new allocation?

**Comment by dxoigmn** [comment]
Something like that. I don't think there is an allocation for batch size of 128 due to the size of the inputs. Recall the the `predict` in PyTorchClassifier does it own batching of the input and typical inputs have the shape `(N, 3, 16, 112, 112)` where `N` is usually much smaller than 128. So PyTorch see inputs of shape like `(8, 3, 16, 112, 112)`. My sense is that for increasing (or perhaps new powers of 2?) `N`, PyTorch is essentially allocating memory for that new shape, but I don't quite grok PyTorch's memory management.

**Comment by seanpmorgan** [comment]
This was fixed in https://github.com/twosixlabs/armory/pull/519/files

**Comment by dxoigmn** [comment]
There seems to be a similar leak on https://github.com/twosixlabs/armory/blob/912ab2addc6771af4660e135908548825a499baf/armory/scenarios/video_ucf101_scenario.py#L137. Since `batch_size` is set to `x.shape[0]`, the same problem happens. You only really see this on video cards with < 12GB of memory though.

**Comment by davidslater** [comment]
@seanpmorgan was unable to replicate the memory leak, and his video card is definitely smaller than 12GB.

**Comment by davidslater** [comment]
@mzweilin believes that the memory leak is due solely to the gradient computation. Can you elaborate on why?

**Comment by dxoigmn** [comment]
@seanpmorgan Did you run through the entire UCF101 test dataset?

**Comment by seanpmorgan** [comment]
> @seanpmorgan Did you run through the entire UCF101 test dataset?

Apologies @dxoigmn you are correct. PR submitted that should fix the issue, but I'm still a bit fuzzy on the underlying issue within ART for doing this. Need to test this on ART 1.3 going forward to see if this is an issue for pytorch native attacks as well
