### ISSUE TITLE
`--port` flag does not seem to work

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [twosixlabs/armory#513]
For example `launch armory-madry --interactive --port 9898` and then: `docker ps -a` yields:

```
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
89003b161f0f        armory-madry                 "tail -f /dev/null"      17 minutes ago      Up 17 minutes                           great_wing
```

Expected behavior is to see a port mapping in the `PORTS` column

Version used is the one from master at the time of writing

**Comment by seanpmorgan** [comment]
Yeah, at the moment ports are only opened with `--jupyter` flag. That should be an easy fix:
https://github.com/twosixlabs/armory/blob/master/armory/eval/evaluator.py#L136
