### ISSUE TITLE
Performance of PyTorch's DataLoader in Armory

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#520]
There seems to be a performance issue when using [torch.utils.data.DataLoader](https://pytorch.org/docs/stable/data.html) in our code. When we set `num_workers` to something greater than 1, the DataLoader is unable to use all of the CPU resources because all of the workers will be on same core. I haven't root-caused why this happens, but I do know that if we import torch before tensorflow, that fixes the issue. The earliest import of tensorflow I can find in Armory is at [armory/data/datasets.py#L16](https://github.com/twosixlabs/armory/blob/master/armory/data/datasets.py#L16).

**Comment by davidslater** [comment]
Do you just need `import torch` to happen before the tensorflow imports, or do you need the DataLoader import to also happen before that?

**Comment by davidslater** [comment]
That also seems to be the earliest import of tensorflow to me. We are working on a pytorch-specific loader that would remove the TF dependencies at runtime, but that is more than a week out, I think. If we added
```
try:
    import torch
except ImportError:
    pass
```
before that line in `datasets.py`, would that solve the issue? It's not a very pretty solution, but I don't anticipate it causing errors.

**Comment by dxoigmn** [comment]
Adding the import before the line does solve the issue.

Here is a minimal example that works when run in Docker. Note that commenting out the art import alleviates the issue, so it's something about the interplay between art, tensorflow and pytorch.

```
#import torch # UNCOMMENT FOR SPEEEEED
import tensorflow
import art

from torchvision.datasets import UCF101
from torchvision import transforms

dataset = UCF101(root='/path/to/movies/UCF-101',
                 annotation_path='/path/to/annotations/ucfTrainTestlist',
                 frames_per_clip=16,
                 num_workers=32)
```

You'll have to edit the dataset paths and install `av` to get this to work.

**Comment by davidslater** [comment]
Digging into the `art` import using `modulefinder`, it potentially performs a lot of imports that include torch and tensorflow, so it would be hard to nail down where the problem may be there.
