### ISSUE TITLE
Image Not Found Error

### ISSUE THREAD

**Issue by hensden** [twosixlabs/armory#544]
On running `sudo ~/.local/bin/armory run scenario_configs/resisc45_baseline_densenet121_finetune.json`

`
Traceback (most recent call last):
  File "/home/rohan/.local/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/rohan/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/twosixarmory/tf1:0.7.0-dev/json
`

**Comment by seanpmorgan** [comment]
Hi @hensden! So if you're running from master branch then you need to build the development images yourself:
https://github.com/twosixlabs/armory/blob/master/docs/contributing.md#development-docker-containers

The published containers are only available for released versions. If you want to use the source code then we'd recommend you use the 0.6 branch:
https://github.com/twosixlabs/armory/blob/master/docs/contributing.md#development-docker-containers:
https://github.com/twosixlabs/armory/tree/r0.6

But if you simply want to use armory then its easiest to just pip install the testbed. See:
https://armory.readthedocs.io/en/latest/getting_started/

**Comment by hensden** [comment]
This error is thrown when I run `sudo bash docker/build-dev.sh tf1`: 
(Also, I am not sure how to specify the version for tf:0.7.0, unless am I supposed to edit Dockerfile?)
```
Traceback (most recent call last): 
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main <br>
    mod_name, _Error) <br>
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "armory/__init__.py", line 24
    print(f"ERROR: cannot import '{module}' module")
                                                  ^
SyntaxError: invalid syntax
invalid argument "twosixarmory/armory:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
invalid argument "twosixarmory/tf1-base:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
invalid argument "twosixarmory/tf1:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
```
- I am running the above in a python-3.6 virtualenv, so not sure about the calls to python-2.7
- The same error as the original post is thrown after checking out to branch `r0.6`.

**Comment by seanpmorgan** [comment]
> This error is thrown when I run `sudo bash docker/build-dev.sh tf1`:
> (Also, I am not sure how to specify the version for tf:0.7.0, unless am I supposed to edit Dockerfile?)
> 
> ```
> Traceback (most recent call last): 
>   File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main <br>
>     mod_name, _Error) <br>
>   File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
>     __import__(mod_name)  # Do not catch exceptions initializing package
>   File "armory/__init__.py", line 24
>     print(f"ERROR: cannot import '{module}' module")
>                                                   ^
> SyntaxError: invalid syntax
> invalid argument "twosixarmory/armory:" for "-t, --tag" flag: invalid reference format
> See 'docker build --help'.
> invalid argument "twosixarmory/tf1-base:" for "-t, --tag" flag: invalid reference format
> See 'docker build --help'.
> invalid argument "twosixarmory/tf1:" for "-t, --tag" flag: invalid reference format
> See 'docker build --help'.
> ```
> 
> * I am running the above in a python-3.6 virtualenv, so not sure about the calls to python-2.7
> * The same error as the original post is thrown after checking out to branch `r0.6`.

Hmmm looks like the script is using `/usr/lib/python2.7` to parse the file. Since we're only compatible with python3 it throws an error on the f-string. Could you try a conda or virtual env so `python` is pointing to a python3.6+ installation

**Comment by hensden** [comment]
Yeah, I have mentioned above, "I am running the above in a python-3.6 virtualenv, so not sure about the calls to python-2.7"

**Comment by seanpmorgan** [comment]
> Yeah, I have mentioned above, "I am running the above in a python-3.6 virtualenv, so not sure about the calls to python-2.7"

Sorry I missed those bullet points. So there is nothing fancy going on in the build-dev scripts (just calls to docker and one call to `python`):
https://github.com/twosixlabs/armory/blob/master/docker/build-dev.sh#L18-L28
It's likely because you're running `sudo` so your removing the virtualenv you're running in. 

Before we go too far down this route is there a reason you need to be using the developer builds and master branch? If you switch to a release branch then the docker images can be pulled from dockerhub:

```
https://github.com/twosixlabs/armory/tree/r0.7
```
