### ISSUE TITLE
Add documentation for adversarial datasets

### ISSUE THREAD

**Issue by seanpmorgan** [twosixlabs/armory#547]
Need to describe the splits and access patterns for using the adversarial datasets.

**Comment by davidslater** [comment]
Closed the wrong issue.

**Comment by davidslater** [comment]
@MITRE folks, can you add something in the docs to describe the adversarial datasets for the scenarios?

**Comment by yusong-tan** [comment]
Do we add to the datasets.md file, or do you want us to create an adversarial_datasets.md file?

**Comment by davidslater** [comment]
Make a separate adversarial_datasets.md file, but link to it from the main datasets.md file.
