### ISSUE TITLE
Overriding configuration options in command line

### ISSUE THREAD

**Issue by mzweilin** [twosixlabs/armory#561]
I wish something like this could be supported in Armory, so that we don't have to create many configuration files in the development phase.

```bash
$ armory run scenario_configs/baseline.json dataset.batch_size=32
```

**Comment by davidslater** [comment]
This seems straightforward for the example you have here, but seems challenging in the broader case.

Do you have thoughts on what a syntax would look like for more complicated structures in the JSON? On the command line, we'll need to worry about escaping characters in bash for the strings, as well as handling more complex structures (adding a metric to a list, for instance).

Thoughts on overall usage here?

**Comment by dxoigmn** [comment]
One way to accomplish this is to accept `stdin` as input for `armory run`. Then we can use [`jq`](https://stedolan.github.io/jq/) to modify the json file:

```
jq ".attack.kwargs.eps = 0.2" scenario_configs/mnist_detector.json | armory run -
```

Should be doable considering armory already saves the json file to the output folder.

**Comment by mzweilin** [comment]
> One way to accomplish this is to accept `stdin` as input for `armory run`. Then we can use [`jq`](https://stedolan.github.io/jq/) to modify the json file:
> 
> ```
> jq ".attack.kwargs.eps = 0.2" scenario_configs/mnist_detector.json | armory run -
> ```
> 
> Should be doable considering armory already saves the json file to the output folder.

I like this solution. Here's a more traditional solution for your reference: https://github.com/huanzhang12/CROWN-IBP/blob/master/argparser.py#L51
