### ISSUE TITLE
documentation for budget  dict in attack configuration

### ISSUE THREAD

**Issue by jesus-villalba** [twosixlabs/armory#574]
For the configuration below, in the librispeech example:
What is the purpose of the "budget" dict?,
Is it the norm that is passed as parameter to the FGSM attack?
If it is why is not just passed in the kwargs dict?
If it is not why not use the same norm as in FGSM (inf)?

"attack": {
        "budget": {  
            "norm": [
                "L2"
            ]
        },
        "knowledge": "white",
        "kwargs": {
            "eps": 0.2
        },
        "module": "art.attacks",
        "name": "FastGradientMethod"
    },

**Comment by seanpmorgan** [comment]
Hi @jesus-villalba thanks for pointing this out. So the budget dictionary is never parsed or utilized. It was left over from some early iterations of the configs. I'll submit a PR to clean these up as it's confusing to users.

We may in the future want to incorporate a similar budget dictionary, but we'll document that appropriately when we do.
