### ISSUE TITLE
Visualization of dataset before and after attack

### ISSUE THREAD

**Issue by hensden** [twosixlabs/armory#577]
Is there any way to visualize the dataset (resisc45) from the TFRecords and what effect an attack has on them?

**Comment by seanpmorgan** [comment]
Hi @hensden! So we created a stub to do this a long time ago so the path forward is there.. but needs to be implemented:
https://github.com/twosixlabs/armory/blob/93beb1a67e76eeb59b34711a4d2a205000e3fcbc/armory/scenarios/base.py#L59-L60

**Comment by lcadalzo** [comment]
This is duplicative with #876
