### ISSUE TITLE
Pre-defined poisoned data splits

### ISSUE THREAD

**Issue by seanpmorgan** [twosixlabs/armory#598]
Per discussions, it'd be a good idea to evaluate poisoning defenses against several pre-defined poisoned data splits. This ensures robustness against different initializations of poisoned samples and also keeps the evaluation consistent for various defenses. This would be in contrast to the current random.choice of images to poison.

**Comment by seanpmorgan** [comment]
Re-opening because we'll want a way to have several different splits be evaluated.

**Comment by davidslater** [comment]
@swsuggs can you comment on whether this is still needed for poisoning evaluations?

**Comment by swsuggs** [comment]
This is no longer of interest to the poisoning group.
