### ISSUE TITLE
Armory spectrogram scenario crashes

### ISSUE THREAD

**Issue by alkaet** [twosixlabs/armory#606]
When running the default spectrogram official scenario with gpu: true 
See the attached error log and scenario json (renamed as txt for github upload)

Run command is done from the armory example directory
`armory run official_scenario_configs/librispeech_spectrogram_external_repo.json`
[librispeech_spectrogram_external_repo.json](https://github.com/twosixlabs/armory/files/4708685/librispeech_spectrogram_external_repo.txt)
[log_spectro.txt](https://github.com/twosixlabs/armory/files/4708686/log_spectro.txt)

**Comment by davidslater** [comment]
Can you rerun in `--no-docker` mode
```
armory run official_scenario_configs/librispeech_spectrogram_external_repo.json --no-docker
```
and see if you run into the same issue?

To be clear, this happens only when gpu is True?

**Comment by alkaet** [comment]
Sorry for the late answer, I got caught up in the submission for which we did found an alternative arrangement.
The no-docker log is attached
[log_no-docker.txt](https://github.com/twosixlabs/armory/files/4898554/log_no-docker.txt)

**Comment by davidslater** [comment]
Current spectrogram scenario is deprecated.
