### ISSUE TITLE
Improving UCF-101 inference speed

### ISSUE THREAD

**Issue by mzweilin** [twosixlabs/armory#609]
The current Armory pipeline takes 1,910 seconds to run one round of UCF101-1 validation on 3,792 videos, while the original MARS pipeline only takes 300 seconds (6.37x faster).

I line-profiled the code and located two bottlenecks:

1. The MARS model is fed with a single group of 16 consecutive frames every time instead of a batch of 16-frame groups;
2. The pillow-based scale-crop in preprocessing is single-threaded.

The fix of bottleneck 1 is in the pull request https://github.com/twosixlabs/armory/pull/608, which brings 2.25x speedup.

However, the inference performance is still 2.83x slower than the original MARS pipeline. A fix to bottleneck 2 may be worth a discussion.

**Comment by mzweilin** [comment]
I believe the memory leak issue in https://github.com/twosixlabs/armory/issues/502 has been handled by the `with torch.no_grad():` statement in the pull request https://github.com/twosixlabs/armory/pull/608.

**Comment by davidslater** [comment]
Are the memory leaks only due to the predict functionality, not due to loss_gradient computation?

**Comment by davidslater** [comment]
Fixed in ART 1.3.0 via IBM/adversarial-robustness-toolbox#448

**Comment by mzweilin** [comment]
> Are the memory leaks only due to the predict functionality, not due to loss_gradient computation?

You are right. loss_gradient has the similar issue. There is an easy fix since batching is supported in ART.Attack.
https://github.com/twosixlabs/armory/issues/502#issuecomment-642355361

**Comment by davidslater** [comment]
Closing this one, but moving the memory leak discussion to #502
