### ISSUE TITLE
Multiple armory runs are always on same CPU?

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#610]
I'm at the point where I want to scale out my `armory run`s. However, when I launch two runs, I see them running on the same CPU. This affects performance because preprocessing happens on the CPU. Is this a known issue?

Here's the output from HTOP with CPU column enabled. Notice the process last run on the same CPU and they both have ~50% CPU usage.
```
    CPU   PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
  1 28023 ccorneli   20   0 45.2G 13.7G  555M R 50.5 10.9  3:18.89 python -m armory.scenarios.base eyJfZGVzY3JpcHRpb24iOiAiVUNGMTAxIHZpZGVvIGNsYXNzaWZpY2F0aW9uIGZyb20gcHJldHJhaW5lZCwgY29udHJpYnV0ZWQgYnkgTUlUUkUgQ29ycG9yYXRpb24iLCAiYWRob2MiOiBudWxsLCAiYXR0YWNrIjogeyJidWRnZXQiOiBudWxsLCAia25vd2xlZGdlIjogIndoaXRlIiwgImt3YXJncyI6IHsiZXBzIjogNTEuMH0sICJtb2R1bGUiOiAiY
  1 28820 ccorneli   20   0 45.7G 12.8G  555M R 49.8 10.2  2:18.18 python -m armory.scenarios.base eyJfZGVzY3JpcHRpb24iOiAiVUNGMTAxIHZpZGVvIGNsYXNzaWZpY2F0aW9uIGZyb20gcHJldHJhaW5lZCwgY29udHJpYnV0ZWQgYnkgTUlUUkUgQ29ycG9yYXRpb24iLCAiYWRob2MiOiBudWxsLCAiYXR0YWNrIjogeyJidWRnZXQiOiBudWxsLCAia25vd2xlZGdlIjogIndoaXRlIiwgImt3YXJncyI6IHsiZXBzIjogNTEuMH0sICJtb2R1bGUiOiAiY
```

**Comment by dxoigmn** [comment]
I just noticed the support for running without docker, so `--no-docker` will mitigate this for now.

**Comment by davidslater** [comment]
On my mac, two runs actually use more than 200% CPU, so it's definitely spreading beyond a single core there. Will try next on ubuntu. What scenario are you running?

**Comment by davidslater** [comment]
I was also unable to replicate this on Ubuntu. This sounds like some sort of Docker configuration issue.

**Comment by dxoigmn** [comment]
Thanks for checking! I will try to root cause now.

**Comment by davidslater** [comment]
@dxoigmn did you get any clarity on this issue?

I recently ran into it again in a different preprocessing function. It looks like the preprocessing only uses a single core (the same single core) but that the training actually uses all cores, so running HTOP it goes back and forth between 100% and 400% usage depending on whether it's doing preprocessing or model fitting.

When running other (non-armory) processes in the container, there is no limit to cores usage.

My guess is that there is some interaction between pytorch and python multiprocessing. I'm trying to put together a minimum working example.

**Comment by dxoigmn** [comment]
@davidslater I wasn't able to. We went with just running `--no-docker`. If I find some time, I'll try to replicate this again and poke around.

**Comment by davidslater** [comment]
Closing. My guess is that there were some weird library interactions due to poor conda / pip installation in our docker containers. Will investigate further if it pops up again, but I haven't seen this particular issue happen recently (and I've seen very high CPU usage on pytorch images)
