### ISSUE TITLE
Make all ART attacks / defenses default kwargs explicit in the configs

### ISSUE THREAD

**Issue by seanpmorgan** [twosixlabs/armory#614]
It has been noted that it would be helpful to explicitly note all parameters for ART attacks / defenses in the configs so that users would better understand how they're being used without needing to dig through ART code to find default parameters.

**Comment by ng390** [comment]
Some parameters, e.g. a norm of np.inf for a ProjectedGradientDescent attack don't have a clean way of being included in the json config. I would lean against updating the scenarios to support this.
