### ISSUE TITLE
Downloading Weights files

### ISSUE THREAD

**Issue by hensden** [twosixlabs/armory#619]
Suppose I want to download a weights file like `densenet121_resisc45_v1.h5`, how would I go about it?

**Comment by seanpmorgan** [comment]
Hi @hensden! Programatically you should use the `download_file_from_s3` function:
https://github.com/twosixlabs/armory/blob/r0.8/armory/data/utils.py#L61-L82

If you just want a url though you can directly download from the public s3 bucket:
https://armory-public-data.s3.us-east-2.amazonaws.com/model-weights/densenet121_resisc45_v1.h5
