### ISSUE TITLE
failed to run with --no-docker and got error "No module named armory.scenarios"

### ISSUE THREAD

**Issue by sissiok** [twosixlabs/armory#666]
Hello, I tried to run without docker but failed. I hope someone could help me figure this out. Below is the details:

sudo python3 armory run --use-gpu --no-docker armory-example/official_scenario_configs/cifar10_baseline.json 

2020-07-08 11:44:20 lambda-dual armory.eval.evaluator[26810] INFO Running evaluation script
/usr/bin/python: No module named armory.scenarios
2020-07-08 11:44:20 lambda-dual armory.eval.evaluator[26810] WARNING Cleaning up...
2020-07-08 11:44:20 lambda-dual armory.eval.evaluator[26810] INFO Deleting tmp_dir /home/xiruo/gard/.armory/tmp/2020-07-08T184420.618734
2020-07-08 11:44:20 lambda-dual armory.eval.evaluator[26810] INFO Removing output_dir /home/xiruo/gard/.armory/outputs/2020-07-08T184420.618734 if empty

System: Ubuntu 18.04.4
Armory version: 0.10.0

**Comment by ng390** [comment]
Are you calling `python3 -m armory run` on a cloned version of the armory repo or using the pip installed version of armory? Do you need to run using sudo?

**Comment by sissiok** [comment]
I used pip to install armory-testbed first. Then I tried python3 -m armory run --no-docker both with sudo and without sudo. But the results are just same: no module named armory.scenarios

**Comment by davidslater** [comment]
If you have armory pip installed, then you shouldn't be calling it with `python3`. You should just call:
```
armory run --use-gpu --no-docker armory-example/official_scenario_configs/cifar10_baseline.json
```

If that doesn't work, can you call the following and drop in the responses:
```
sudo python3 armory --version 
python3 armory --version
armory --version
sudo armory --version
which armory
sudo which armory
ls
```

**Comment by sissiok** [comment]
Now I downgraded it to armory version 0.9.1 and tried to use `armory run` directly, but it still has the same issue. Below is the details:

xiruo@lambda-dual:~/gard$ armory run --no-docker --use-gpu armory-example/official_scenario_configs/mnist_baseline.json 
2020-07-13 15:13:10 lambda-dual armory.eval.evaluator[17529] INFO Running evaluation script
/usr/bin/python: No module named armory.scenarios
2020-07-13 15:13:10 lambda-dual armory.eval.evaluator[17529] WARNING Cleaning up...
2020-07-13 15:13:10 lambda-dual armory.eval.evaluator[17529] INFO Deleting tmp_dir /home/xiruo/.armory/tmp/2020-07-13T221310.101729
2020-07-13 15:13:10 lambda-dual armory.eval.evaluator[17529] INFO Removing output_dir /home/xiruo/.armory/outputs/2020-07-13T221310.101729 if empty
xiruo@lambda-dual:~/gard$ sudo python3 armory --version
/usr/bin/python3: can't find '__main__' module in 'armory'
xiruo@lambda-dual:~/gard$ python3 armory --version
/usr/bin/python3: can't find '__main__' module in 'armory'
xiruo@lambda-dual:~/gard$ armory --version
0.9.1
xiruo@lambda-dual:~/gard$ sudo armory --version
sudo: armory: command not found
xiruo@lambda-dual:~/gard$ which armory
/home/xiruo/.local/bin/armory
xiruo@lambda-dual:~/gard$ sudo which armory
xiruo@lambda-dual:~/gard$

**Comment by davidslater** [comment]
Can you do
```
ls armory
```

**Comment by davidslater** [comment]
(from your `~/gard` directory)

**Comment by davidslater** [comment]
my guess is that you have a folder named "armory" in your "~/gard" directory, which is messing up the python pathing when running armory.

**Comment by davidslater** [comment]
try the following:
```
cd ~/gard/armory-example
armory run --use-gpu --no-docker official_scenario_configs/cifar10_baseline.json
```

**Comment by sissiok** [comment]
Here is what I see:

`
xiruo@lambda-dual:~/gard$ ls armory
armory                 LICENSE      requirements.txt  test-requirements.txt
docker                 MANIFEST.in  scenario_configs  tests
docs                   mkdocs.yml   setup.py          tools
host-requirements.txt  README.md    STYLE.md
xiruo@lambda-dual:~/gard$ cd armory-example/
xiruo@lambda-dual:~/gard/armory-example$ armory run --use-gpu --no-docker official_scenario_configs/mnist_baseline.json 
2020-07-13 15:42:31 lambda-dual armory.eval.evaluator[17940] INFO Running evaluation script
/usr/bin/python: No module named armory.scenarios
2020-07-13 15:42:31 lambda-dual armory.eval.evaluator[17940] WARNING Cleaning up...
2020-07-13 15:42:31 lambda-dual armory.eval.evaluator[17940] INFO Deleting tmp_dir /home/xiruo/.armory/tmp/2020-07-13T224231.600766
2020-07-13 15:42:31 lambda-dual armory.eval.evaluator[17940] INFO Removing output_dir /home/xiruo/.armory/outputs/2020-07-13T224231.600766 if empty
xiruo@lambda-dual:~/gard/armory-example$ 

`

**Comment by davidslater** [comment]
This is quite bizarre. Alright, try the following:
In bash:
```
echo $PATH
```
Then jump into a python interpreter, import armory, and print the file path:
```
$ python
>>> import armory
>>> armory.__file__
```
I get something like 
```
'/Users/davidslater/git/twosixlabs/armory/__init__.py'
```

Do this for both python and python3, and see if they're different.

**Comment by sissiok** [comment]
My path is `/home/xiruo/.poetry/bin:/home/xiruo/.poetry/bin:/home/xiruo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
`
I installed armory with python3, so nothing is there with python2.
`xiruo@lambda-dual:~/gard$ python
Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import armory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named armory
>>> exit()
xiruo@lambda-dual:~/gard$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import armory
>>> armory.__file__
'/home/xiruo/.local/lib/python3.6/site-packages/armory/__init__.py'
>>> 
`

**Comment by davidslater** [comment]
A couple more things. What do you get for these:
```
more /home/xiruo/.local/lib/python3.6/site-packages/armory/init.py
ls /home/xiruo/.local/lib/python3.6/site-packages/armory
ls /home/xiruo/.local/lib/python3.6/site-packages/armory/scenarios
```

And in python, what does it give as your python path:
```
python
>>> import sys
>>> print(sys.path)
```

This one is quite the puzzle!

**Comment by sissiok** [comment]
xiruo@lambda-dual:~/gard$ more /home/xiruo/.local/lib/python3.6/site-packages/armory/init.py
more: stat of /home/xiruo/.local/lib/python3.6/site-packages/armory/init.py failed: No such file or directory
xiruo@lambda-dual:~/gard$ ls /home/xiruo/.local/lib/python3.6/site-packages/armory
art_experimental  data    __init__.py  __pycache__  webapi
baseline_models   docker  __main__.py  scenarios
configuration.py  eval    paths.py     utils
xiruo@lambda-dual:~/gard$ ls /home/xiruo/.local/lib/python3.6/site-packages/armory/scenarios/
audio_classification.py  image_classification.py      __pycache__
base.py                  __init__.py                  video_ucf101_scenario.py
download_configs         poisoning_gtsrb_scenario.py


xiruo@lambda-dual:~/gard$ more /home/xiruo/.local/lib/python3.6/site-packages/armory/init.py
more: stat of /home/xiruo/.local/lib/python3.6/site-packages/armory/init.py failed: No such file or directory
xiruo@lambda-dual:~/gard$ ls /home/xiruo/.local/lib/python3.6/site-packages/armory
art_experimental  data    __init__.py  __pycache__  webapi
baseline_models   docker  __main__.py  scenarios
configuration.py  eval    paths.py     utils
xiruo@lambda-dual:~/gard$ ls /home/xiruo/.local/lib/python3.6/site-packages/armory/scenarios/
audio_classification.py  image_classification.py      __pycache__
base.py                  __init__.py                  video_ucf101_scenario.py
download_configs         poisoning_gtsrb_scenario.py


Thanks for helping me to figure this out! It looks like very challenging.

**Comment by davidslater** [comment]
I think we're getting close. Can you try:
```
cd ~/gard/armory-example
armory run --use-gpu --no-docker official_scenario_configs/cifar10_baseline.json
```

Also, give the result of 
```
ls ~/gard
```

**Comment by davidslater** [comment]
I think we're getting close. Can you try:
```
cd /home/xiruo/.local/lib/python3.6/site-packages
armory run --use-gpu --no-docker ~/gard/armory-example/official_scenario_configs/cifar10_baseline.json
```

Also, give the result of 
```
ls ~/gard
```

**Comment by sissiok** [comment]
xiruo@lambda-dual:~/gard$ cd /home/xiruo/.local/lib/python3.6/site-packages

xiruo@lambda-dual:~/.local/lib/python3.6/site-packages$ armory run --use-gpu --no-docker ~/gard/armory-example/official_scenario_configs/cifar10_baseline.json 

2020-07-13 16:52:15 lambda-dual armory.eval.evaluator[18716] INFO Running evaluation script
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 462, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 472, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 428, in iter_importers
    __import__(pkg)
  File "armory/__init__.py", line 24
    print(f"ERROR: cannot import '{module}' module")
                                                  ^
SyntaxError: invalid syntax
2020-07-13 16:52:15 lambda-dual armory.eval.evaluator[18716] WARNING Cleaning up...
2020-07-13 16:52:15 lambda-dual armory.eval.evaluator[18716] INFO Deleting tmp_dir /home/xiruo/.armory/tmp/2020-07-13T235215.118053
2020-07-13 16:52:15 lambda-dual armory.eval.evaluator[18716] INFO Removing output_dir /home/xiruo/.armory/outputs/2020-07-13T235215.118053 if empty


xiruo@lambda-dual:~/.local/lib/python3.6/site-packages$ python3 armory run --use-gpu --no-docker ~/gard/armory-example/official_scenario_configs/cifar10_baseline.json 

ERROR: cannot import 'docker.errors' module
    Please run: $ pip install -r requirements.txt
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "armory/__main__.py", line 19, in <module>
    import docker
  File "armory/docker/__init__.py", line 5, in <module>
    from armory.docker import management
  File "/home/xiruo/.local/lib/python3.6/site-packages/armory/__init__.py", line 17, in <module>
    from armory import eval
  File "/home/xiruo/.local/lib/python3.6/site-packages/armory/eval/__init__.py", line 5, in <module>
    from armory.eval.evaluator import Evaluator
  File "/home/xiruo/.local/lib/python3.6/site-packages/armory/eval/evaluator.py", line 14, in <module>
    from docker.errors import ImageNotFound
ModuleNotFoundError: No module named 'docker.errors'

xiruo@lambda-dual:~$ pip3 show docker

Name: docker
Version: 4.2.1
Summary: A Python library for the Docker Engine API.
Home-page: https://github.com/docker/docker-py
Author: None
Author-email: None
License: Apache License 2.0
Location: /home/xiruo/.local/lib/python3.6/site-packages
Requires: websocket-client, requests, six


xiruo@lambda-dual:~/.local/lib/python3.6/site-packages$ ls ~/gard

armory          armory-sender-INTL.tar.gz  scenario_runner-0.9.9
armory-example  GARD                       scenario_runner-v0.9.8
armory-notes    gard_xiruo.code-workspace

**Comment by davidslater** [comment]
One more thing: try running this:
```
more $(which armory)
```

I get something like this:
```
#!/Users/davidslater/opt/anaconda3/envs/armory-pip-test/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from armory.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

Then take the resulting path from the first line and call it with `--version` like the following:
```
/Users/davidslater/opt/anaconda3/envs/armory-pip-test/bin/python --version
```

I get 
```
Python 3.6.10 :: Anaconda, Inc.
```

**Comment by sissiok** [comment]
The path I got is /usr/bin/python3 

xiruo@lambda-dual:~/.local/lib/python3.6/site-packages$ /usr/bin/python3 --version

Python 3.6.9

**Comment by davidslater** [comment]
I really have no idea what is going on in your system. The main clue that I have is that when you do
```
xiruo@lambda-dual:~/.local/lib/python3.6/site-packages$ armory run --use-gpu --no-docker ~/gard/armory-example/official_scenario_configs/cifar10_baseline.json
```
you get
```
2020-07-13 16:52:15 lambda-dual armory.eval.evaluator[18716] INFO Running evaluation script
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
mod_name, _Error)
File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
loader = get_loader(mod_name)
File "/usr/lib/python2.7/pkgutil.py", line 462, in get_loader
return find_loader(fullname)
File "/usr/lib/python2.7/pkgutil.py", line 472, in find_loader
for importer in iter_importers(fullname):
File "/usr/lib/python2.7/pkgutil.py", line 428, in iter_importers
import(pkg)
File "armory/init.py", line 24
print(f"ERROR: cannot import '{module}' module")
```

At no point should it enter into python2.7, so I canonly conclude that there is some error related to one of a) your system pathing, b) your python installations, or c) how armory was installed. I have no ability to replicate your error on our systems, and there is no indication that there is an error in the armory codebase, as "armory.scenarios" is clearly a module in our codebase.

My recommendation is to install conda https://docs.conda.io/en/latest/ , and then install armory and its requirements inside a conda environment. If the issue persists even in a conda environment, let me know. Or, try running it in a docker container.

**Comment by sissiok** [comment]
Thank you very much for your help! I will try conda.

**Comment by davidslater** [comment]
Going to close the issue, but if you are unable to get it to run on conda, let me know and we can reopen it.

**Comment by dxoigmn** [comment]
I helped debug this issue and it appears to be a bug in Armory when running outside of a virtual environment/conda. The reason is due to:

https://github.com/twosixlabs/armory/blob/7dd5de4cc3f13d7c0e6d5106cdfe0d52d1a5b4f9/armory/eval/evaluator.py#L243

On most systems, `python` defaults to python2, but in virtual environments `python` defaults to whatever version of python was used to setup the virtual environment. The easy fix is to change the `python` to `python3` but it really should re-use the same python that armory was invoked with.

**Comment by davidslater** [comment]
The most straightforward way to do this, that I can think of, is to use `sys.executable` when running in `--no-docker` mode:
```
f"{sys.executable} -m armory.scenarios.base {b64_config}{options}", **kwargs
```

Thoughts @dxoigmn ?

**Comment by dxoigmn** [comment]
> The most straightforward way to do this, that I can think of, is to use `sys.executable` when running in `--no-docker` mode:
> 
> ```
> f"{sys.executable} -m armory.scenarios.base {b64_config}{options}", **kwargs
> ```
> 
> Thoughts @dxoigmn ?

An even better solution!
