### ISSUE TITLE
Add DARPA to README and potentially other places.

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#677]
"This material is based upon work supported by the Defense Advanced Research Projects Agency (DARPA) under Contract No. HR001120C0114. Any opinions, findings and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the Defense Advanced Research Projects Agency (DARPA)."

@ng390 Thoughts on places other than the main README that this would go? Perhaps somewhere in the docs for readthedocs. Anywhere else?

**Comment by ng390** [comment]
If we add it to docs/index.md in addition to the main README it will show up in readthedocs. It probably should also be added to the README in armory-example.

**Comment by davidslater** [comment]
That makese sense as well.

**Comment by davidslater** [comment]
Let's wait on this until #678 is done.
