### ISSUE TITLE
Confirm if ART attack is targeted after loading

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#682]
Armory's scenario code determines whether an attack is targeted by [parsing](https://github.com/twosixlabs/armory/blob/master/armory/scenarios/image_classification.py#L94) the config and assumes False is there's nothing in the config to specify it's targeted. However, some ART [attacks](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/1.2.0/art/attacks/evasion/boundary.py#L61) are targeted by default.

This causes an issue when `targeted: false` isn't explicitly set in the attack config for an ART attack that's targeted by default. In this case, ART will [error](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/1.2.0/art/attacks/evasion/boundary.py#L152) if `use_label: false` or incorrectly use the _true_ labels to measure targeted attack success rate if `use_label: true`. This latter case caused me to see attack success rates of 100%, while accuracy on adversarial examples was also 100%

**Comment by davidslater** [comment]
Would requiring `targeted` in the config be sufficient to address this?

**Comment by lcadalzo** [comment]
just seeing this comment...my commit a second ago instead raises a warning (rather than asserting).

To answer your question, yes it would.

**Comment by davidslater** [comment]
Let's go the warning direction for now, and then possibly revisit after evaluations. I like the idea of making the config manditory, but don't want to change all of the configs now.
