### ISSUE TITLE
Add targeted label schemes for scenarios

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#688]

**Comment by DavidN-EmbedIntel** [comment]
btw: one gotcha with targeted label schemes is that you currently need to set 'targeted=True' when you instantiate the attack.

If you don't, and it defaults to False, you can still pass it target labels and it will fail silently, i.e. find attacks that are successful, but don't ever cause the estimator to classify the attacked image as the target label

You might be well aware of this already but just in case thought I'd point that out

**Comment by davidslater** [comment]
Yep, we're aware, thanks! In particular, if targeted=False, then the attack will optimize for **not** the label.

**Comment by DavidN-EmbedIntel** [comment]
yes thank you for saying that in 5 words instead of 20 :)
