### ISSUE TITLE
Identifying errors when running scenarios in CI testing

### ISSUE THREAD

**Issue by ng390** [twosixlabs/armory#698]
Currently, when calling `armory run` to run scenarios from json configs in the CI testing, the return code is not captured. It is necessary to manually look at the logs to see if a scenario succeeds or fails in running. This can be corrected by finding a way to capture the return codes of the scenario run (passed through docker) or by parsing the log for "error" statements.

**Comment by adamj26** [comment]
Per https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.exec_run , it appears that `exec_run()`, which armory uses to run the scenario in the container, can return either the error code for the command or streaming logs from stdout and stderr, but not both, so we will have to parse the log for error statements to determine if the container
