### ISSUE TITLE
Inaccurate error message when requirements from `host-requirements.txt` are not installed

### ISSUE THREAD

**Issue by adamj26** [twosixlabs/armory#704]
If one runs armory without ART (for example) installed in the environment, one gets the following error message:

```
$ python -m armory --help
ERROR: cannot import 'art' module
    Please run: $ pip install -r requirements.txt
```

But ART is in `host-requirements.txt`, not `requirements.txt`.

The error message should be changed to mention `host-requirements.txt`

**Comment by davidslater** [comment]
This only occurs on the PR branch #706 due to some import changes there. Will fix on that branch and close this issue.
