### ISSUE TITLE
Config_scheme.json out-of-date with respect to supported metrics

### ISSUE THREAD

**Issue by yusong-tan** [twosixlabs/armory#728]
Please update https://github.com/twosixlabs/armory/blob/98a3782966e627f7412909b00a7075e5e04e2c7b/armory/utils/config_schema.json#L183-L196 to reflect all metrics supported under armory.utils.metrics

If metrics such as "perturbation: 'snr'" is set, then the json validation fails schema.

**Comment by davidslater** [comment]
I think that your version is not up to date - I fixed this a week ago with a PR. Current master: https://github.com/twosixlabs/armory/blob/master/armory/utils/config_schema.json

**Comment by davidslater** [comment]
https://github.com/twosixlabs/armory/blob/master/armory/utils/config_schema.json#L190-L219
