### ISSUE TITLE
Canonicalize Librispeech preprocessing

### ISSUE THREAD

**Issue by ng390** [twosixlabs/armory#750]
- [x] Need to finalize canonical preprocessing format for Librispeech
- [x] Need to implement canonical preprocessing for Librispeech
- [x] Need to update sincnet preprocessing
- [x] Need to update sincnet_full preprocessing

**Comment by davidslater** [comment]
Remaining Items:
- [ ] Enable fit mode with preprocessing
- [ ] Update tests
