### ISSUE TITLE
discover a mechanism to provide "rootless" containers

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#774]
It would be good to provide container users with container management that doesn't require root on the hosting system.

This is a stub issue with considerable refinement needed about the semantics of "rootless"

**Comment by davidslater** [comment]
Good discussion of issues: https://jtreminio.com/blog/running-docker-containers-as-current-host-user/

**Comment by christopherwoodall** [comment]
Possible duplicate of [1029](https://github.com/twosixlabs/armory/issues/1029).

**Comment by mwartell** [comment]
Fixed in #1786
