### ISSUE TITLE
Update xView dataset to make a "canonical" label format for OD

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#777]
Should be very close to estimator output.

**Comment by lcadalzo** [comment]
I believe this is duplicative with #785 (I must've not noticed this issue was created). If so, could you close this issue?

**Comment by davidslater** [comment]
The two are slightly different (this one focuses on datasets where the other focuses on model outputs). Let's keep them both open until the fix is done.

**Comment by lcadalzo** [comment]
To clarify, #785 refers to modifying the dataset keys of xView (as well as APRICOT) from `'bbox'` and `'category_id'` to `'boxes'` and `'labels'` respectively. The latter pair represents the "canonical" format. #785 does not entail any modification of model outputs

**Comment by davidslater** [comment]
#793 #794
