### ISSUE TITLE
Update UCF101 video dataset to remove artifacts

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#791]
There are two issues producing artifacts:
1) ffmpeg is not called with the highest quality, producing video compression artifacts.
2) the frames are saved as jpeg, which introduces additional artifacts.

I propose modifying the TFDS file to build the dataset with high quality video extraction and keeping it saved in the original video format (not saving as frames).

**Comment by davidslater** [comment]
If I understand this correctly, this would involve modifying this line from TFDS:
https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/video/ucf101.py#L125-L129
The change would add '-q:v 2' to ffmpeg_extra _args in this line.

This is the frame extraction line in the MARS script:

https://github.com/craston/MARS/blob/master/utils1/extract_frames.py#L48
(The MARS script rescales images, which we don't need. TFDS correctly leaves the scale untouched.)

As far as storage, a lossless format may be preferable to jpeg. But it might be best to just use the MARS settings (i.e., store frames and flows as jpegs), so those relying on the pre-trained MARS model see an Armory performance consistent with the MARS validation scripts.

**Comment by mzweilin** [comment]
Hi @davidslater , are we going to get a new TFDS anytime soon?

**Comment by davidslater** [comment]
Hi @mzweilin sorry for the delay. I'm hoping to have one out tomorrow, but I have been prioritizing bugs, which have been popping up rather rapidly this past couple weeks.
