### ISSUE TITLE
Build Kubernetes API

### ISSUE THREAD

**Issue by seanpmorgan** [twosixlabs/armory#8]
We need to establish a dedicated AWS kubernetes cluster that can handle requests to run ARMORY in the cloud:
https://github.com/twosixlabs/armory/blob/master/armory/webapi/kubeflow_aws.py

- [ ] Create scalable kubernetes cluster on AWS
- [ ] Create API to run ARMORY
- [ ] Determine method of hiding API keys from end-users (possibly a second install-able package?)

**Comment by davidslater** [comment]
Changed focus to ECS for scaling, issues #471 #473 #474 #475
