### ISSUE TITLE
armory.art_experimental.defences.jpeg_compression_normalized returns outputs of type float64

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#838]
The `JpegCompressionNormalized` defense in `armory.art_experimental.defences.jpeg_compression_normalized` turns `float32`s into `float64`s. This causes errors with the MARS classifier since it expects `float32`s. The underlying issue is actually in `art.defences.preprocessor.JpegCompression`, but I imagine this can be taken care of in Armory until ART fixes.

**Comment by davidslater** [comment]
Looking into it, I think it's actually an issue in armory, here:
https://github.com/twosixlabs/armory/blob/master/armory/art_experimental/defences/jpeg_compression_normalized.py#L41-L44

Since the operations are not in place, it promotes the resulting array to float64.
