### ISSUE TITLE
UCF101 scenario epsilons are too large

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#862]
Given the c14n of datasets in Armory 0.12, the attack `eps` value in the UCF101 scenarios is too large now (51), which means the attacker is always successful. These values should be normalized to `[0, 1]` range. I imagine a similar analysis should be done for the other scenarios to make sure the `eps` values are in the correct range.

**Comment by davidslater** [comment]
Thanks for noting this. I made a fix. Checking the other scenarios, they appear to be properly scaled. Audio is a bit weird, as the scale can vary quite a bit more than images/video, but linf is not a great metric in that space.
