### ISSUE TITLE
UCF101 baseline scenario OOM error during attack phase

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#869]
I am seeing out of memory errors during the `ucf101_baseline_pretrained.json` scenario on our Titan Xp 12GB GPUs. I see this happening after the 2760th example (of 3783 total) during the attack phase of the scenario. My hunch is the change to processing whole videos is the cause since now ART needs to compute gradients with respect to the whole video at once. This may be due to memory not be freed appropriately (i.e., there needs to be a `del` placed somewhere) or the 2760th example (+- 1 example, perhaps) may be just too large to fit on the GPU.

**Comment by davidslater** [comment]
I'm guessing that you're running into this in the attack?

Looking into the dataset, the 2760th [0-indexed] example is the second largest in the dataset, with size 880x240x320x3, or 202,752,000 input dimensions. The 3313rd example is the actual largest in the test set, with 900x240x320x3 or 207,360,000 input dimensions.

So, I don't think that this is a memory leak, just a very large input sample. 

The 2258th example has size 844x240x320x3 = 194457600 input dimensions, which you successfully passed, so you probably have almost enough memory. I think that the most straightforward way to handle this would be to truncate the end of the video to a set number of frames to prevent out of memory errors, which could be easily done in the forward pass of the baseline model.

Thoughts?

**Comment by davidslater** [comment]
Truncating to 512 frames should leave sufficient memory to work for an 8 GB card, and would only affect 1% of the test set.

**Comment by dxoigmn** [comment]
Yes, during the attack phase of the scenario. I tried running the pipeline just on the 3313rd example and I get an OOM. So you're probably correct that this is just too large of a video. I suppose truncating the video is one way to get this working, assuming truncation does not cause a disagreement between the label and truncated video content.
