### ISSUE TITLE
Issue while running APRICOT Scenario in --no-docker mode

### ISSUE THREAD

**Issue by paperwhite** [twosixlabs/armory#872]
The baremetal installation (host-requirements.txt) seems outdated since it installs an older version of ART. APRICOT scenario is compatible only with ART version 1.4.2 - which is specified in the Dockerfile (this version is not yet available with pypi, and can be installed only from the git repo)

Please modify the host-requirements.txt with recent versions.

**Comment by ng390** [comment]
Thanks for bringing this to our attention. I went through the Dockerfiles to confirm versions and linked a PR that updates host-requirements.txt. I am creating a separate issue for the pytorch-deepspeech container, as there will be some version updates to the container shortly (See Issue #787).
