### ISSUE TITLE
Confirm element order in slices of datasets matches original order of unsliced datasets

### ISSUE THREAD

**Issue by ng390** [twosixlabs/armory#895]
Confirm order in slices of datasets matches original order of unsliced datasets. Ordering issue noted in UCF101 test dataset--may only apply to larger datasets.

**Comment by davidslater** [comment]
@ng390 Can you provide the example you spoke of that doesn't match?

**Comment by ng390** [comment]
For the UCF101 scenario, if we run a scenario on the MARS model with "eval_split": "test[[332,333]]" we do not get a shape warning, however if we run a scenario with the full test split, then the 333rd example does give a warning.

**Comment by davidslater** [comment]
The slice operator in TFDS does not guarantee ordering between different types of splits, only that the same split is repeatable. Generally, it's meant as an easy way to break things into large test/validate/train sets.

The primary other operator that we could use is `tf.data.datasets.split()`, but this still requires full processing, so it's probably better to handle it in our data generator logic.
https://github.com/tensorflow/tensorflow/issues/44008#issuecomment-719740026

**Comment by davidslater** [comment]
The `skip` function does not present computation of dataset items, it just discards them. https://www.tensorflow.org/api_docs/python/tf/data/Dataset#skip

Therefore, I think it is much easier to handle this in our own code. The main challenge will be when the data spans multiple batches.
