### ISSUE TITLE
TORCH_HOME set incorrectly for --no_docker

### ISSUE THREAD

**Issue by alevine0** [twosixlabs/armory#938]
In `__main__.run()`, the Evaluator object is instantiated before `paths.set_mode()` is ever run. This results in `rig.extra_env_vars["TORCH_HOME"]` being set to "/armory", rather than "~/.armory", in the --no_docker case, causing permission errors. This should be a simple one-line fix, by adding the line:

`paths.set_mode("host" if args.no_docker else "docker")`

before 
`rig = Evaluator(config, no_docker=args.no_docker, root=args.root)`

**Comment by davidslater** [comment]
Made a minor change in evaluator, as this affects `launch` and `exec` modes as well.
