### ISSUE TITLE
PyTorch 1.7 support?

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#943]
Are there plans to upgrade PyTorch to 1.7? The one feature that is useful to us is that the `torchvision==0.8.0` ([which depends upon PyTorch 1.7](https://github.com/pytorch/vision)) now [supports (batched) transforms on tensors with multiple channels](https://github.com/pytorch/vision/issues/2292) (previously it only supported transforms on `PIL.Image`). I know there are a lot of dependencies to consider, hence the ask.

**Comment by davidslater** [comment]
We plan to move there eventually, but not before this round of submissions. However, if you were to create a custom container with those dependencies, it shouldn't cause any problems that I am aware of.
