### ISSUE TITLE
Chainable Preprocessor Defenses

### ISSUE THREAD

**Issue by mzweilin** [twosixlabs/armory#957]
ART has added support to efficient-chainable preprocessor defenses in PyTorch and Tensorflow since v1.4.0.

Is there a plan to add such a feature in Armory? It will make us easier to test combinations of preprocessor defenses.

**Comment by davidslater** [comment]
We are considering adding these directly to the configs. We are considering an alternative where we combine model + defense pieces in the config, which which push ART preprocessor pieces into your code.

I would recommend for now just modifying `get_art_model` and adding the preprocessing defenses when you instantiate the ART wrapper.

**Comment by davidslater** [comment]
We're going to be removing the "defense" field of the config and effectively subsuming it under "model", so this for the time being is best handled by the model developer directly.
