### ISSUE TITLE
Failed in ucf101_mars

### ISSUE THREAD

**Issue by sissiok** [twosixlabs/armory#959]
In `armory/armory/baseline_models/pytorch/ucf101_mars.py` , it failed at the following line as `None` is not a valid type here. Suggest to change the default for `max_frames` to `0`

https://github.com/twosixlabs/armory/blob/17a8c2992646a321b804056ad31c53760cc68f1d/armory/baseline_models/pytorch/ucf101_mars.py#L270

**Comment by davidslater** [comment]
TIL: `int(None)` is not allowed. I figured casing would turn it to 0, similar to how bool works `bool(None)` is False. I think I missed this in testing because of directly setting max_frames to 0 in the config.

**Comment by davidslater** [comment]
Fixed in https://github.com/twosixlabs/armory/commit/1383e6980dba63251a024fc158112cc268fd9ec6
