### ISSUE TITLE
currently PoisoningAttackCleanLabelBackdoor cannot find in art

### ISSUE THREAD

**Issue by bettyttytty** [twosixlabs/armory#960]
In file poison_loader_clbd.py, clean label attack is imported from art,
from art.attacks.poisoning import PoisoningAttackCleanLabelBackdoor
but I cannot find this attack in adversarial-robustness-toolbox/art/attacks/poisoning/, so does it only integrate into the docker file? And we can only call this function in the docker currently, while cannot see how it implements now?

**Comment by ng390** [comment]
As of 11/23, the attack is available as part of the dev_1.5.0 branch of ART, and can be found at https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/dev_1.5.0/art/attacks/poisoning/clean_label_backdoor_attack.py. In the Docker container we pinned to commit hash 9d5489911590a7aaa90ae2293b28a0a63e995c42

**Comment by ng390** [comment]
Issue no longer applies with update to ART.
