### ISSUE TITLE
Changing attack_modality in so2sat classification is not effective.

### ISSUE THREAD

**Issue by Lodour** [twosixlabs/armory#961]
The official so2sat's scenario config specifies the modality in `scenario/kwargs/attack_modality`, but changing it to "sar", "eo", and "both" has the same adversarial accuracy. Unless we specify the `attack/generate_kwargs/channels` accordingly.

https://github.com/twosixlabs/armory-example/blob/master/official_scenario_configs/so2sat_baseline.json

My distill is as follows.

The scenario `So2SatClassification` creates the `attack_channels` from `attack/generate_kwargs/channels`, and then from `scenario/kwargs/attack_modality` if the previous one is not specified.

https://github.com/twosixlabs/armory/blob/master/armory/scenarios/multimodal_so2sat_scenario.py#L62-L74

This `attack_channels` is then passed to the attack class via `generate_kwargs["mask"]`.

https://github.com/twosixlabs/armory/blob/master/armory/scenarios/multimodal_so2sat_scenario.py#L255-L261

However, this mask is ignored in `PGDPatch`, which re-creates the channels only from `attack/generate_kwargs/channels`.

https://github.com/twosixlabs/armory/blob/master/armory/art_experimental/attacks/pgd_patch.py#L24

**Comment by ng390** [comment]
The configs have been updated in [amory-example](https://github.com/twosixlabs/armory-example/tree/master/official_scenario_configs) with the channels argument included as a workaround. Will leave the issue open as we may patch the scenario and/or attack in the next release.
