### ISSUE TITLE
add usage of `num_eval_batches` to documentation

### ISSUE THREAD

**Issue by Embeddave** [twosixlabs/armory#966]
Hi two-six labs,

Just thinking it might be good to add usage of `num_eval_batches` to the documentation, specifically the correct way to specify it in the .json config files. I didn't find any docs on it, either here or in `armory-example`.

It's a handy way to debug configs and quickly iterate on experiments.
Also good to be able to document that option in a file.

I had to experiment a little to figure it out -- thought that it should be in scenario/kwargs at first.
Correct usage is just to add it as a key-val pair at the level of scenario, correct? Like so:

```json
    "scenario": {
        "kwargs": {},
        "module": "armory.scenarios.image_classification",
        "name": "ImageClassificationTask",
        "num_eval_batches": 4
    },
```

**Comment by lcadalzo** [comment]
CLI usage of `--num-eval-batches` is included in `docs/command_line.md`, and #1027 added documentation on how to specify in the config file (in `docs/configuration_files.md`)
