### ISSUE TITLE
external repository loader assumes "master" branch exists (which is no longer a valid assumption)

### ISSUE THREAD

**Issue by alevine0** [twosixlabs/armory#975]
The external repository loader in `armory/utils/external_repo.py` assumes, if no branch is selected, that the correct branch is 'master'. However, due to recent changes in GitHub (https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/) there is no longer a 'master' branch for new repositories by default.

There is an easy workaround for now (simply specify @main in the config file), but this could be fixed one of two ways:

1. Try both @master and @main if no branch specified.

 2. If no branch is specified, simply leave the branch off of the get request to github (i.e., just request `https://api.github.com/repos/XXX/YYY/tarball/`): this appears to yield identical results as specifying master or main

**Comment by lcadalzo** [comment]
Hi @alevine0, thanks for reporting this issue with Armory. We have implemented a fix in the PR mentioned above which will appear in the next release of Armory.
