### ISSUE TITLE
channel_first for MARS model is not set correctly

### ISSUE THREAD

**Issue by sissiok** [twosixlabs/armory#988]
MARS model has channel as its last dimension in `input_shape`, so `channel_first` should set to `False` in https://github.com/twosixlabs/armory/blob/d4d3e781cdcf01b83ce21b708f3357e538b2026c/armory/baseline_models/pytorch/ucf101_mars.py#L306 . Otherwise `channel_first` will be set to `True` by default.

**Comment by ng390** [comment]
Closed by #1037
