### ISSUE TITLE
partition utils.metrics for better discovery and composition

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#993]
Per Slater:

Consider changing our metrics setup a bit and migrating armory.utils.metrics to its own top level space armory.metrics with modules for different types, like perturbation, task, and compute. It’s a bit of a messy module at the moment.

It would be nice to make metrics discoverable and addressable, and automatically enable batchwise or elementwise usage
Like `metrics.perturbation.element.l2` or `metrics.perturbation.batch.linf` or `metrics.task.batch.categorical_accuracy`.

**Comment by davidslater** [comment]
This makes nearly all of the metrics element-wise, which I think will greatly simplify testing. Batchwise versions of metrics are automatically generated.
