### ISSUE TITLE
Update docker dependencies

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#997]
Pytorch 1.7? TF 2.4? TF 1.15.5? Python 3.9?

Update what makes sense. TF 2.4 is not in conda, so probably wait on that one?

**Comment by lcadalzo** [comment]
we should consider CUDA (and potentially [py]Docker) updates as well

**Comment by davidslater** [comment]
Potentially 11.2.1-cudnn8-runtime-ubuntu20.04 (11.2.1/ubuntu20.04-x86_64/devel/cudnn8/Dockerfile)
